(function(){
'use strict';
const root=document.getElementById('schematics');
if(!root)return;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const N=(id,title,sub,state,color,input,output,enable,parts,measure,symptom,next)=>({id,title,sub,state,color,input,output,enable,parts,measure,symptom,next});
const DEV={
 phone:{name:'Telefon / smartfon',icon:'📱',warning:'Odłącz baterię przed pomiarem rezystancji i lutowaniem. Nie wstrzykuj napięcia na szynę bez ustalenia jej wartości nominalnej.',states:['Źródło energii obecne','Szyny always-on','Sekwencja startowa','System uruchomiony'],nodes:[
  N('source','USB-C / bateria','VBUS • VBAT',0,'#dc6570','5–20 V z USB-PD lub około 3,0–4,4 V z baterii','VBUS/VBAT na złączu i torze wejścia','Przewód USB, BMS baterii, NTC/ID','port USB-C, złącze baterii, NTC, ID','Napięcie baterii pod obciążeniem; VBUS na porcie; rezystancja głównej linii bez zasilania.','Brak reakcji na przewód, 0 A, wyłączanie pod obciążeniem.','Jeśli napięcie jest na złączu, przejdź do ochrony i układu power-path.'),
  N('protect','Ochrona i charger','ESD • OVP • CC',1,'#e99a43','VBUS/VBAT','VSYS / linia systemowa','CC1/CC2, EN, termistor, komunikacja','TVS, ESD, OVP, charger IC, MOSFET power-path','Spadek przez OVP/MOSFET; VSYS; linie CC; pobór z ładowarki.','5 V na porcie, lecz brak ładowania lub brak napięcia za OVP.','Prawidłowe VSYS kieruje do PMIC; brak — sprawdź EN, zwarcie i układ chargera.'),
  N('alw','PMIC – always-on','RTC • 1V8_AON',1,'#d6bd45','VSYS / VBAT','RTC, 1,8 V AON, czasem 3,0 V AON','Power-good z wejścia, zegar 32 kHz','PMIC, cewki buck, LDO, kondensatory','Rezystancja cewek; szyny AON; temperatura PMIC; zegar RTC.','Stały niski pobór, brak reakcji POWER, grzanie PMIC.','Jeśli AON brak, zbadaj PMIC i obciążenie. Jeśli są, sprawdź przycisk, zegar i reset.'),
  N('control','POWER / zegar / reset','PWRKEY • RESET',2,'#4aa2df','AON + PWRKEY','Sygnały enable kolejnych szyn','PWRKEY, RESET, 32 kHz, sekwencer PMIC','przycisk/flex, generator, reset supervisor','Zmiana PWRKEY przy naciśnięciu; RESET; aktywność zegara; reakcja poboru.','AON jest, ale pobór nie zmienia się po POWER.','Brak PWRKEY — flex lub linia. PWRKEY jest — sprawdź polecenia i kolejne wyjścia PMIC.'),
  N('rails','Główne szyny PMIC','CORE • RAM • I/O',2,'#567dd8','VBAT/VSYS + enable','VCORE, VDDRAM, 1,8 V, 1,2 V, 0,8–1,0 V','EN, sekwencja, PGOOD','przetwornice buck, LDO, cewki, kondensatory','Obserwuj napięcia na cewkach podczas startu; porównaj rezystancje i kolejność.','Skok poboru i spadek, restart, szybkie grzanie elementu.','Pierwsza brakująca szyna wyznacza sektor. Sprawdź jej przetwornicę i odbiorniki.'),
  N('soc','SoC + RAM','CPU • pamięć operacyjna',2,'#806fd1','CORE, RAM, I/O, zegary','Sterowanie pamięcią i peryferiami','RESET zwolniony, zegar główny, PGOOD','SoC/AP, RAM, oscylator, linie danych','Zegary, reset, termika, charakter poboru; porównanie ze sprawną płytą.','Zawieszenie na stałym poborze, brak kolejnego etapu, nadmierne grzanie SoC.','Jeśli warunki SoC są poprawne, sprawdź komunikację z pamięcią rozruchową.'),
  N('storage','UFS / eMMC / NAND','BOOT • firmware',3,'#aa68b8','1,8 V + zasilanie rdzenia pamięci','Dane startowe systemu','RESET, CLK, linie CMD/DATA','UFS/eMMC/NAND, filtry, rezystory terminujące','Napięcia pamięci, aktywność CLK/CMD/DATA, log USB/UART jeśli dostępny.','Logo i restart, recovery, brak zakończenia startu, błędy pamięci.','Potwierdź zasilania i sygnały przed programowaniem lub wymianą pamięci.'),
  N('loads','Ekran / RF / audio','Peryferia końcowe',3,'#4abf96','Szyny lokalne i dane z SoC','Obraz, sieć, dźwięk, kamery','ENABLE, MIPI, I²C, SPI, wzmacniacze','display PMIC, backlight, RF, audio codec, kamery','Zasilania lokalne, sygnały enable, złącza FPC, aktywność magistral.','Telefon startuje, lecz nie działa jedna funkcja.','Zawęź do konkretnego peryferium; nie wracaj do głównego PMIC, jeśli system pracuje stabilnie.')],sym:{dead:'source',short:'rails',boot:'storage',image:'loads',function:'loads'}},
 laptop:{name:'Laptop',icon:'💻',warning:'Przed pomiarem rezystancji odłącz zasilacz i baterię. Przy zasilaniu z USB-C ustal negocjowany profil PD.',states:['Wejście zasilania','S5 / always-on','S3 → S0 / start','System pracuje'],nodes:[
  N('input','DC-IN / USB-C PD','19–20 V • negocjacja',0,'#dc6570','Zasilacz 19–20 V lub USB-C 5 V przed negocjacją','VIN za gniazdem/PD','CC/PD, identyfikacja zasilacza','gniazdo, bezpiecznik, TVS, kontroler USB-PD','VIN, CC1/CC2, profil PD, rezystancja wejścia, stan gniazda.','Brak diody ładowania, 5 V zamiast 20 V USB-C, zwarcie wejścia.','Jeśli prawidłowe VIN dociera do MOSFET-ów, przejdź do toru wejściowego i chargera.'),
  N('charger','MOSFET-y i charger','ACOK • BQ/ISL',1,'#e99a43','VIN','B+ / VSYS / główna szyna 19 V','ACDET, ACDRV, ACOK, CMSRC','MOSFET wejściowy, charger, shunt, kondensatory','Napięcia G/S/D MOSFET-ów, ACDET, ACOK, prąd ładowania, spadek na shuncie.','19 V przed MOSFET-em, 0 V za nim; cykanie zasilacza; brak ładowania.','Brak otwarcia MOSFET-ów: sprawdź zwarcie wyjścia i warunki chargera.'),
  N('alw','3,3 V / 5 V ALW','S5 rails',1,'#d6bd45','19 V / bateria','+3VALW, +5VALW, RTC','ENLDO / EN1 / EN2','kontroler buck 3/5 V, cewki, LDO RTC','Napięcia na cewkach, PGOOD, rezystancje do masy, tętnienia.','Laptop całkowicie martwy lub resetuje się bez reakcji POWER.','Jeśli ALW są stabilne, sprawdź EC/KBC, BIOS i sygnał przycisku.'),
  N('ec','EC / KBC / RTC','RSMRST# • PWRBTN#',1,'#56a5d8','3,3 V ALW + RTC','Sygnały sekwencji S5/S3/S0','PWRBTN#, RSMRST#, lid, AC_PRESENT','EC/KBC, kwarc 32 kHz, przycisk, BIOS EC','3,3 V na EC, zegar, RSMRST#, reakcja PWRBTN#, komunikacja z BIOS.','ALW są, ale brak reakcji lub tylko mignięcie diody.','PWRBTN dochodzi do EC? Jeśli tak, śledź SLP_S5#/SLP_S3# i enable przetwornic.'),
  N('sequence','Sekwencja S5 → S3 → S0','SLP • PGOOD',2,'#567dd8','Polecenia EC/PCH','Szyny RAM, SoC, peryferiów','SLP_S5#, SLP_S3#, ALL_SYS_PWRGD','PCH/SoC, sekwencer, logic gates','Kolejność enable i PGOOD; pierwsza linia, która nie zmienia stanu.','Włącza się na sekundę, pętla startu, pobór rośnie i spada.','Brak PGOOD jednej szyny zatrzymuje sekwencję — sprawdź tę przetwornicę i obciążenie.'),
  N('core','CPU / SoC / RAM VRM','VCORE • VDDQ',2,'#806fd1','19 V/5 V + enable','VCORE, VCCSA, VDDQ, RAM','VR_ON, SVID, PGOOD','PWM wielofazowy, MOSFET-y, cewki, CPU, RAM','Napięcia i tętnienia na cewkach, sygnały PWM, termika, pobór.','Wentylator rusza i gaśnie, brak obrazu, zwarcie na cewce.','Niska rezystancja VCORE może być normalna. Oceniaj wraz z poborem i termiką.'),
  N('boot','BIOS / zegary / reset','SPI • PLTRST#',3,'#aa68b8','3,3 V + warunki PCH/SoC','Kod inicjalizacji, PLTRST#','SPI_CS#, CLK, RESET, RTC','pamięć SPI BIOS, oscylatory, PCH/SoC','Aktywność SPI po POWER, zasilanie BIOS, zegary, PLTRST#, pobór POST.','Zasilania są, brak POST/obrazu, restart po kilku sekundach.','Zrób kopię wsadu i porównaj odczyty. Nie programuj przed potwierdzeniem zasilania i sygnałów.'),
  N('periph','Ekran / dysk / USB','eDP • SATA/NVMe',3,'#4abf96','Szyny S0 i sygnały SoC','Obraz, pamięć masowa, porty','LCD_EN, BL_EN, PERST#, CLKREQ#','matryca, eDP, NVMe, USB, audio','LCDVDD, BL_EN, sygnał eDP, zasilania NVMe, enumeracja USB.','Laptop działa na monitorze zewnętrznym lub nie widzi jednego urządzenia.','Jeśli POST przechodzi, diagnozuj gałąź peryferium zamiast całej sekwencji.')],sym:{dead:'input',short:'alw',boot:'boot',image:'periph',function:'periph'}},
 tv:{name:'Telewizor LED/LCD',icon:'📺',warning:'Strona pierwotna zasilacza może mieć około 325 V DC, a z aktywnym PFC około 380–400 V DC. Wymagane są odpowiednie kwalifikacje i sprzęt.',states:['Sieć i DC BUS','STBY','PS_ON / start','Obraz i dźwięk'],nodes:[
  N('ac','Wejście 230 V','FUSE • EMI • MOV',0,'#dc6570','230 V AC','AC za filtrem','Wyłącznik / bezpiecznik','bezpiecznik, MOV, NTC, filtr EMI','Bez napięcia: bezpiecznik i zwarcia. Pod napięciem tylko bezpiecznie: AC za filtrem.','Martwy TV, przepalony bezpiecznik, ponowne przepalanie.','Nie wymieniaj bezpiecznika w ciemno. Sprawdź mostek, MOSFET i kondensator główny.'),
  N('bus','Mostek i DC BUS','325 V DC • PFC',0,'#e99a43','230 V AC','około 310–325 V DC; po PFC zwykle 380–400 V','PFC_ON po starcie','mostek, kondensator 400–450 V, PFC, MOSFET, dioda','Napięcie kondensatora głównego, zwarcie mostka/MOSFET-a, PFC_ON.','Bezpiecznik dobry, brak DC BUS; PFC nie podnosi napięcia po starcie.','DC BUS prawidłowy — przejdź do STBY. Brak — zostań po stronie pierwotnej.'),
  N('standby','Zasilacz STBY','3,3 V / 5 V',1,'#d6bd45','DC BUS','STBY do płyty MAIN','Samostart PWM / VCC układu','PWM standby, transformator, transoptor, TL431','STBY na złączu, VCC PWM, impulsy bramki, zwarcie wtórne, tętnienia.','Brak diody standby, cykanie, pulsowanie napięcia.','Stabilne STBY kieruje do MAIN. Pulsowanie — sprawdź sprzężenie i obciążenie.'),
  N('mainctl','MAIN – sterowanie startem','PS_ON • BL_ON',2,'#56a5d8','STBY','PS_ON do PSU, BL_ON/PWM do LED','Przycisk/IR, reset, firmware','SoC standby, eMMC, IR, regulator lokalny','Lokalne 3,3/1,8 V, reset, PS_ON podczas próby, pobór płyty.','Dioda reaguje, lecz brak PS_ON; restart logo; zawieszenie.','PS_ON brak przy dobrym STBY wskazuje MAIN. PS_ON jest — sprawdź szyny robocze PSU.'),
  N('psu','Główne wyjścia PSU','12 / 13 / 24 V',2,'#567dd8','DC BUS + PS_ON','Szyny główne do MAIN/audio/T-CON','PS_ON, PFC_OK','PWM główny, MOSFET, transformator, prostowniki','Wyjścia opisane na złączu, tętnienia, reakcja na PS_ON, spadek pod obciążeniem.','TV próbuje startować, napięcia pojawiają się i znikają.','Odłącz obciążenia zgodnie z procedurą; ustal, czy PSU się zabezpiecza, czy brak sterowania.'),
  N('soc','SoC / eMMC / DDR','MAIN BOARD',2,'#806fd1','12 V → lokalne buck/LDO','LVDS/eDP, audio, sterowania','RESET, zegary, PGOOD, firmware','SoC, eMMC, DDR, buck 5/3,3/1,8/1,2 V','Wszystkie cewki, reset, aktywność eMMC, temperaturę SoC, sygnał LVDS/eDP.','Logo i restart, brak menu, brak HDMI/tunera, grzanie SoC.','Gdy SoC startuje i wysyła obraz, przejdź do T-CON/panelu; brak danych — zostań na MAIN.'),
  N('panel','T-CON / panel','AVDD • VGH • VGL',3,'#aa68b8','12 V / sygnał obrazu','Napięcia matrycy i sterowanie bramek','PANEL_ON, LVDS/eDP','bezpiecznik SMD, DC/DC, gamma, level shifter, COF','Bezpiecznik, wejście, AVDD/VGH/VGL/VCOM według panelu, sygnał wejściowy.','Podświetlenie jest, lecz brak treści; biały ekran; połowa obrazu; pasy.','Nie podawaj obcych napięć. Porównuj połówki panelu i taśmy dopiero po sprawdzeniu zasilania.'),
  N('output','LED driver / audio','BL_ON • AMP_EN',3,'#4abf96','12/24 V + sterowanie MAIN','Podświetlenie i dźwięk','BL_ON, PWM_DIM, AMP_MUTE/EN','driver LED, listwy, wzmacniacz audio, głośniki','BL_ON/PWM, napięcie LED, tester listew, zasilanie audio i MUTE.','Obraz pod latarką, mignięcie podświetlenia, brak dźwięku.','BL_ON obecne i driver wyłącza się — sprawdź listwy. BL_ON brak — wróć do MAIN.')],sym:{dead:'ac',short:'bus',boot:'mainctl',image:'panel',function:'output'}},
 desktop:{name:'Komputer stacjonarny',icon:'🖥️',warning:'Zasilacz ATX zawiera stronę sieciową. Nie otwieraj go bez przygotowania. Pomiary na płycie wykonuj z ochroną przed zwarciem sondą.',states:['AC i +5VSB','Standby płyty','PS_ON / POST','System pracuje'],nodes:[
  N('atx','Zasilacz ATX','AC → +5VSB',0,'#dc6570','230 V AC','+5VSB','Własny układ standby PSU','PSU, bezpiecznik, standby SMPS','+5VSB na fioletowym przewodzie, test pod obciążeniem, tętnienia.','Brak reakcji i brak LED płyty, 0 V na +5VSB.','Brak +5VSB oznacza PSU/wejście. Jest — przejdź do sekcji standby płyty.'),
  N('boardalw','Standby płyty','3V3_AUX • RTC',1,'#d6bd45','+5VSB + bateria CMOS','3,3 V AUX, RTC','Zasilanie Super I/O/PCH standby','LDO/buck AUX, bateria CR2032, kondensatory','3,3 V AUX, RTC, zwarcia, temperatura elementów standby.','+5VSB jest, brak reakcji POWER, grzanie na płycie.','Jeśli AUX prawidłowe, sprawdź Super I/O i sygnał przycisku.'),
  N('sio','Super I/O / PWRBTN','PS_ON#',1,'#56a5d8','3,3 V AUX + PWRBTN#','PS_ON# do zasilacza','Przycisk, reset, BIOS/EC firmware','Super I/O, przycisk, układ resetu','PWRBTN# zmienia stan; PS_ON# schodzi nisko; sygnały reset/clock.','Brak reakcji przy prawidłowym standby albo start tylko po zwarciu PS_ON.','PWRBTN dochodzi, PS_ON nie wychodzi — sprawdź warunki SIO/PCH i BIOS.'),
  N('rails','Szyny ATX','12 V • 5 V • 3,3 V',2,'#e99a43','PS_ON#','12 V, 5 V, 3,3 V, PWR_OK','PS_ON# i zabezpieczenia PSU','złącza ATX/EPS, PSU, przewody','Wszystkie szyny pod obciążeniem, PWR_OK, spadki na złączach, tętnienia.','Wentylatory drgną, pętla włączania, brak PWR_OK.','Brak jednej szyny — PSU/złącze/obciążenie. Wszystkie są — przejdź do VRM.'),
  N('vrm','VRM CPU / RAM / PCH','VCORE • VDIMM',2,'#567dd8','12 V EPS + 3,3/5 V','Niskie szyny rdzenia','VR_ON, PWM, PGOOD','kontroler PWM, MOSFET/DrMOS, cewki, kondensatory','Napięcia na cewkach, zwarcia, PWM, PGOOD, termika faz.','Start i natychmiast stop, brak POST, grzanie jednej fazy.','Najpierw ustal brakującą szynę. VCORE ma naturalnie niską rezystancję.'),
  N('logic','PCH / CPU / zegary','RESET • CLK',2,'#806fd1','VCORE, VCCSA, PCH, RAM','Inicjalizacja platformy','PWR_OK, PLTRST#, zegary','CPU, PCH, generator zegara, reset','Zegary, reset, PGOOD, kolejność zasilania, kod POST.','Zasilania są, brak kodu POST lub zatrzymanie na jednym etapie.','Kod debug/diody płyty wskażą blok: CPU, DRAM, VGA albo BOOT.'),
  N('biosram','BIOS i RAM','SPI • DDR',3,'#aa68b8','3,3 V BIOS + VDIMM','Kod POST i trening pamięci','SPI_CS#, CLK, RESET, SPD','pamięć BIOS, moduły RAM, sloty, linie SPD','Aktywność SPI, odczyt BIOS, napięcie RAM, test pojedynczego modułu/slotu.','Pętla POST, kod DRAM, brak zapisu ustawień, brak obrazu.','Zrób kopię BIOS przed zapisem. Testuj RAM i sloty pojedynczo.'),
  N('io','GPU / PCIe / NVMe','Obraz i urządzenia',3,'#4abf96','Szyny robocze + PCIe','Obraz, dysk, USB, sieć','PERST#, CLKREQ#, enable GPU','GPU, sloty PCIe, NVMe, USB, LAN','Zasilania GPU/NVMe, link PCIe, PERST#, wykrywanie w BIOS.','POST przechodzi, lecz brak obrazu lub urządzenia.','Diagnozuj konkretną gałąź po potwierdzeniu, że platforma kończy POST.')],sym:{dead:'atx',short:'vrm',boot:'biosram',image:'io',function:'io'}},
 tablet:{name:'Tablet',icon:'▣',warning:'Procedura zbliżona do telefonu, ale ekran i podświetlenie mogą pobierać większą moc. Odłącz baterię przed pracą na złączach FPC.',states:['USB / bateria','Always-on','Start SoC','System i ekran'],nodes:[
  N('source','USB-C / bateria','VBUS • VBAT',0,'#dc6570','5–20 V USB-C lub pakiet 1S/2S','VBUS/VBAT','CC, NTC, ID','port, BMS, złącze, zabezpieczenia','Napięcie baterii, VBUS, CC, spadki na złączu.','Nie ładuje, 1%, brak reakcji, wyłącza się.','Prawidłowe źródło kieruje do chargera i power-path.'),
  N('charge','Charger / power-path','VSYS',1,'#e99a43','VBUS/VBAT','VSYS i prąd ładowania','EN, NTC, komunikacja','charger IC, OVP, MOSFET, shunt','VSYS, prąd, temperatura, spadek na MOSFET-ach.','Bateria dobra, VBUS obecne, ale brak VSYS lub ładowania.','Sprawdź warunki chargera i zwarcie linii systemowej.'),
  N('pmic','PMIC / AON','RTC • 1V8',1,'#d6bd45','VSYS','Szyny always-on','PGOOD, RTC','PMIC, LDO, cewki','AON, zegar, rezystancje cewek, termika.','Martwy tablet mimo poprawnego VSYS.','AON brak — PMIC/obciążenie. AON jest — POWER/reset.'),
  N('start','POWER / reset','Sekwencja PMIC',2,'#56a5d8','AON + PWRKEY','Enable głównych szyn','PWRKEY, RESET, zegary','flex POWER, PMIC, oscylatory','Reakcja poboru i napięć na naciśnięcie POWER.','Brak zmiany poboru albo krótki impuls i stop.','Śledź pierwszą szynę, która nie pojawia się lub zanika.'),
  N('core','SoC / RAM','CORE • VDDQ',2,'#806fd1','Główne szyny','Sterowanie pamięcią i peryferiami','RESET, CLK, PGOOD','SoC, RAM, buck/LDO','Napięcia, zegary, reset, termika, pobór.','Stały pobór bez obrazu, restart, grzanie SoC.','Poprawne warunki SoC kierują do pamięci startowej.'),
  N('boot','eMMC / UFS','BOOT',3,'#aa68b8','Szyny pamięci','System operacyjny','CLK/CMD/DATA','pamięć, filtry, firmware','Napięcia i aktywność magistrali, tryb recovery/USB.','Logo i restart, recovery, brak zakończenia startu.','Wyklucz zasilanie i sygnały przed zapisem lub wymianą pamięci.'),
  N('display','LCD / backlight','MIPI • LED',3,'#4abf96','VBAT/boost + dane SoC','Obraz i podświetlenie','LCD_EN, BL_EN, PWM','display PMIC, boost LED, FPC, matryca','Zasilania LCD, BL_EN/PWM, napięcie LED, złącza.','Tablet działa i wydaje dźwięki, ale ekran czarny lub bez podświetlenia.','Testuj znanym ekranem dopiero po sprawdzeniu zasilania i sterowania.'),
  N('periph','Audio / Wi-Fi / kamery','Peryferia',3,'#52b8a6','Szyny lokalne','Funkcje końcowe','I²C/SPI/MIPI/SDIO','kodek, wzmacniacze, RF, kamery','Zasilania, enable, magistrale, złącza.','Jedna funkcja nie działa przy stabilnym systemie.','Zawęź do lokalnego regulatora, złącza i magistrali urządzenia.')],sym:{dead:'source',short:'core',boot:'boot',image:'display',function:'periph'}},
 console:{name:'Konsola do gier',icon:'🎮',warning:'Nie wymieniaj retimera HDMI bez potwierdzenia zasilania, zegarów i sygnałów. Przy APU/BGA kontroluj profil termiczny i stan padów.',states:['Zasilacz wejściowy','Standby','Sekwencja APU','System / HDMI'],nodes:[
  N('psu','Zasilacz / wejście','12 V • standby',0,'#dc6570','230 V AC lub zewnętrzny adapter','12 V i standby','AC detect / power request','PSU, gniazdo, bezpieczniki','Napięcia wyjściowe bez i pod obciążeniem, tętnienia, złącze.','Brak diody, cykanie PSU, napięcie zanika po podłączeniu płyty.','Stabilne napięcie wejściowe kieruje do zabezpieczeń płyty.'),
  N('input','Ochrona / MOSFET-y','MAIN 12 V',1,'#e99a43','12 V','Główna szyna płyty','EN / soft-start','MOSFET-y, shunt, TVS, kondensatory','Rezystancja 12 V, spadek przez MOSFET-y, pobór i termika.','PSU się wyłącza, zwarcie 12 V, grzanie MOSFET-a.','Zwarcie lokalizuj przed pełnym zasileniem. Brak zwarcia — sprawdź standby.'),
  N('standby','Southbridge / standby','3V3 • 1V8 AON',1,'#d6bd45','12 V','Szyny always-on','PGOOD, RTC','standby buck/LDO, southbridge, zegar','AON, zegar, reset, reakcja przycisku/eject.','Brak reakcji na przycisk mimo prawidłowego 12 V.','Jeśli AON i przycisk są prawidłowe, śledź polecenie uruchomienia VRM.'),
  N('seq','Sterowanie sekwencją','EN • PGOOD',2,'#56a5d8','AON + POWER','Enable kolejnych VRM','reset, clock, power request','southbridge, sekwencer, logika','Kolejność EN/PGOOD oraz zmiana poboru podczas próby.','Konsola włącza się i natychmiast gaśnie.','Pierwsze brakujące PGOOD wskazuje podejrzaną szynę lub jej obciążenie.'),
  N('vrm','VRM APU / RAM','CORE • SOC • GDDR',2,'#567dd8','12 V + enable','Niskie szyny APU i pamięci','PWM, PGOOD','DrMOS/MOSFET, cewki, APU, GDDR','Napięcia na cewkach, fazy PWM, termika, zwarcia.','Duży pobór, brak startu, jedna faza grzeje, pętla zasilania.','Niska rezystancja rdzenia może być normalna; porównaj fazy i termikę.'),
  N('apu','APU / RAM / zegary','BOOT INIT',2,'#806fd1','CORE/SOC/RAM','Inicjalizacja pamięci i systemu','RESET, CLK, PGOOD','APU, GDDR/DDR, oscylatory','Zegary, reset, temperaturę, charakter poboru, sygnały do pamięci.','Zasilania obecne, brak dalszego startu lub przegrzewanie APU.','Poprawna inicjalizacja kieruje do pamięci systemowej/firmware.'),
  N('storage','NAND / SSD / firmware','SYSTEM BOOT',3,'#aa68b8','Szyny pamięci','System konsoli','CLK/CMD/DATA, security','NAND/eMMC/SSD, kontroler, firmware','Zasilania, aktywność magistrali, tryb recovery, log UART jeśli dostępny.','Błąd systemu, recovery, zatrzymanie na logo.','Zabezpiecz klucze i dane unikalne przed programowaniem pamięci.'),
  N('hdmi','HDMI / USB / napęd','Wyjścia końcowe',3,'#4abf96','Szyny I/O + dane APU','Obraz i urządzenia','HDMI_EN, HPD, zegary','retimer/redriver HDMI, ESD, encoder, port','Zasilania retimera, HPD, zegary, linie TMDS/FRL właściwym sprzętem.','Konsola uruchamia się, lecz brak obrazu albo portu USB.','Najpierw port/ESD/zasilania/zegary, dopiero potem wymiana retimera.')],sym:{dead:'psu',short:'input',boot:'storage',image:'hdmi',function:'hdmi'}},
 smps:{name:'Zasilacz impulsowy SMPS',icon:'⚡',warning:'Strona pierwotna jest połączona z siecią i kondensator może długo utrzymywać niebezpieczne napięcie. Do pomiarów potrzebna jest separacja i odpowiednie sondy.',states:['Wejście AC / DC BUS','Start PWM','Praca przetwornicy','Regulowane wyjście'],nodes:[
  N('emi','Bezpiecznik i EMI','AC INPUT',0,'#dc6570','230 V AC','AC po filtrze','Bezpiecznik / NTC','F, MOV, NTC, dławik CM, kondensatory X/Y','Bez zasilania: ciągłość bezpiecznika, zwarcia MOV/mostka, oględziny.','Brak pracy, przepalony bezpiecznik, ślady udaru.','Przepalony bezpiecznik wymaga znalezienia zwarcia dalej, nie tylko wymiany.'),
  N('rect','Mostek i kondensator','DC BUS',0,'#e99a43','230 V AC','około 310–325 V DC','Brak — prostowanie pasywne','mostek, kondensator bulk, PFC opcjonalny','DC BUS, tętnienia, diody mostka, ESR/pojemność bulk po rozładowaniu.','Brak DC mimo AC, duże tętnienia, bezpiecznik przepala.','Prawidłowy BUS kieruje do zasilania startowego PWM.'),
  N('startup','Start VCC kontrolera','UVLO',1,'#d6bd45','DC BUS przez rezystor/startup','VCC PWM','Próg UVLO układu','rezystory startowe, VCC capacitor, uzwojenie AUX','VCC narasta do progu? Czy zapada cyklicznie? Sprawdź kondensator VCC.','Cykanie, krótkie próby, brak stałych impulsów bramki.','VCC nie osiąga progu — tor startowy. Osiąga i spada — AUX, przeciążenie lub zabezpieczenie.'),
  N('switch','PWM + MOSFET','PRIMARY SWITCH',2,'#567dd8','DC BUS + VCC PWM','Impulsy w uzwojeniu pierwotnym','Gate drive, current sense','kontroler PWM, MOSFET, shunt, snubber','Impulsy bramki, zwarcie D-S, sygnał current sense, snubber.','MOSFET zwarty, brak impulsów, praca burst, nagrzewanie.','Brak gate przy poprawnym VCC — warunki PWM. Gate jest, brak transferu — MOSFET/transformator/obciążenie.'),
  N('transformer','Transformator impulsowy','Izolacja',2,'#806fd1','Impulsy pierwotne','Napięcia wtórne i AUX','Sprzężenie magnetyczne','transformator, uzwojenia, izolacja','Ciągłość, test zwojów/LCR, przebiegi odpowiednią sondą, temperatura.','Piszczenie, brak jednego uzwojenia, grzanie, niestabilna praca.','Wyklucz zwarcie wtórne przed podejrzeniem transformatora.'),
  N('secondary','Prostowniki wtórne','DC OUTPUT',2,'#aa68b8','Impulsy wtórne','5/12/24 V zależnie od konstrukcji','Przewodzenie diod/synchroniczne','Schottky/synch rectifier, dławik, kondensatory','Diody, zwarcia, napięcia, tętnienia, ESR kondensatorów.','Niskie/pulsujące wyjście, grzanie diody, duże tętnienia.','Odłącz obciążenie kontrolowanie; sprawdź, czy problem leży w PSU czy odbiorniku.'),
  N('feedback','Sprzężenie zwrotne','TL431 • opto',3,'#4abf96','Napięcie wyjściowe','Informacja regulacyjna do PWM','Dzielnik napięcia','TL431, transoptor, dzielnik, kompensacja','Napięcie REF TL431, transoptor, rezystory dzielnika, stabilność pętli.','Wyjście za wysokie/niskie, pulsowanie mimo sprawnych elementów mocy.','Błąd dzielnika lub opto zmienia regulację. Sprawdź także obciążenie minimalne.'),
  N('load','Filtr i obciążenie','Stabilne wyjście',3,'#52b8a6','Regulowane DC','Zasilanie odbiornika','PGOOD / obciążenie','filtr LC, złącza, odbiornik','Spadek pod obciążeniem, tętnienia, temperatura, przewody i styki.','Napięcie bez obciążenia dobre, po podłączeniu zanika.','Rozdziel ograniczenie PSU od zwarcia lub nadmiernego poboru odbiornika.')],sym:{dead:'emi',short:'switch',boot:'startup',image:'secondary',function:'feedback'}},
 agd:{name:'Moduł AGD – pralka/zmywarka',icon:'🧺',warning:'Moduł AGD pracuje z 230 V. Grzałka, silnik, pompy i triaki są obwodami sieciowymi. Odłącz urządzenie i rozładuj kondensatory przed pomiarami bez napięcia.',states:['Wejście sieciowe','Zasilanie logiki','Program startuje','Elementy wykonawcze'],nodes:[
  N('mains','230 V / filtr / blokada','AC INPUT',0,'#dc6570','230 V AC','AC do zasilacza i mocy','Wyłącznik, filtr, blokada drzwi','filtr EMI, wyłącznik, zamek, złącza','Ciągłość przewodu, filtr, napięcie wejściowe, stan blokady wg schematu.','Urządzenie całkowicie martwe lub nie rozpoczyna programu.','Zasilanie dochodzi — przejdź do SMPS. Brak — wejście, przewód, filtr, blokada.'),
  N('smps','SMPS modułu','5 V • 12 V',1,'#e99a43','230 V AC','5 V logiki, 12 V przekaźników','Samostart PWM','rezystor fusible, LNK/TNY, transformator, diody, elektrolity','5/12 V, tętnienia, ESR, rezystor startowy, zwarcie wtórne.','Wyświetlacz martwy, buczenie, cykliczne próby, reset programu.','Stabilne zasilania kierują do MCU/resetu. Pulsujące — napraw zasilacz lub usuń przeciążenie.'),
  N('mcu','MCU / reset / zegar','LOGIC',1,'#d6bd45','5/3,3 V','Sterowania i komunikacja','RESET, kwarc, watchdog','mikrokontroler, EEPROM, kwarc, reset','Zasilanie MCU, RESET, zegar, aktywność magistral, termika.','Napięcia są, lecz panel nie reaguje lub zawiesza się.','Brak reset/clock zatrzymuje logikę. Jeśli MCU startuje, sprawdź wejścia bezpieczeństwa.'),
  N('inputs','Czujniki i warunki startu','NTC • poziom • drzwi',2,'#56a5d8','5/12 V z modułu','Sygnały do MCU','Drzwi, poziom wody, NTC, flow','NTC, hydrostat, kontaktron, czujnik zalania','Rezystancje i zmiana sygnału, wiązka, 5 V referencji, live/service mode.','Program nie startuje, stoi na etapie, błędnie grzeje lub napełnia.','Sterownik nie uruchomi wyjść bez spełnienia warunków bezpieczeństwa.'),
  N('drivers','Przekaźniki / triaki','STEROWANIE MOCĄ',2,'#567dd8','5/12 V + polecenie MCU','230 V przełączane do odbiornika','Gate/base/coil drive','ULN, optotriak, triak, przekaźnik, tranzystor','Sygnał sterujący, napięcie cewki, styki pod obciążeniem, zwarcie triaka.','MCU wydaje polecenie, ale odbiornik nie działa lub działa stale.','Brak sterowania — wróć do warunków wejściowych. Sterowanie jest — sprawdź driver i tor mocy.'),
  N('pumps','Pompy i zawory','WODA',3,'#4aa2df','230 V z drivera','Przepływ / odpompowanie','Polecenie MCU','pompa odpływowa, myjąca, elektrozawory','Napięcie pod obciążeniem, rezystancja uzwojenia, mechanika, drożność, prąd.','Nie pobiera lub nie wypompowuje wody, tylko czasami działa.','Jeśli napięcie jest, sprawdź pompę/mechanikę. Jeśli brak — driver, złącze, wiązka lub warunek programu.'),
  N('heatmotor','Grzałka / silnik','DUŻA MOC',3,'#aa68b8','230 V z przekaźnika/triaka','Ciepło / ruch','Warunki temperatury/poziomu','grzałka, silnik, falownik, przekaźnik','Rezystancja, izolacja do PE, prąd, napięcie pod obciążeniem, czujnik temperatury.','Nie grzeje, wybija zabezpieczenie, silnik nie rusza lub szarpie.','Przed podaniem zasilania potwierdź izolację i warunki bezpieczeństwa.'),
  N('feedback','Sprzężenie i ochrona','PRĄD • TEMP • TACHO',3,'#4abf96','Reakcja odbiornika','Potwierdzenie dla MCU','Tacho, NTC, shunt, czujnik przepływu','tachogenerator/Hall, NTC, shunt, presostat','Czy sygnał zmienia się wraz z pracą? Porównaj polecenie z informacją zwrotną.','Element rusza i zaraz staje, błąd mimo sprawnego odbiornika.','Brak potwierdzenia powoduje wyłączenie ochronne — sprawdź czujnik, wiązkę i wejście MCU.')],sym:{dead:'mains',short:'smps',boot:'inputs',image:'mcu',function:'drivers'}}
};

const STATE_NAMES=['Źródło / OFF','STANDBY / ALW','START / sekwencja','RUN / pełna praca'];
const SYM=[['dead','Całkowicie martwe'],['short','Zwarcie / duży pobór'],['boot','Nie kończy startu'],['image','Brak obrazu / wyjścia'],['function','Nie działa jedna funkcja']];
let current='phone',state=3,mode='map',selected=null;

root.innerHTML='<h1>🗺️ Schematy płyt PRO</h1><p class="muted">Klikalne mapy blokowe pokazujące drogę energii, sygnały sterujące i kolejność uruchamiania sektorów.</p><div class="spHero"><h2>Od źródła zasilania do działającego urządzenia</h2><p>Wybierz urządzenie i stan sekwencji. Zielone bloki powinny być aktywne; przygaszone jeszcze nie muszą pracować. Kliknij sektor, aby zobaczyć pomiary i decyzję diagnostyczną.</p><div class="spControls"><label>Urządzenie<select id="spDevice"></select></label><label>Stan sekwencji<select id="spState"></select></label><label>Widok<select id="spMode"><option value="map">Mapa graficzna</option><option value="sequence">Tabela sekwencji</option><option value="rails">Tory i szyny zasilania</option></select></label></div></div><div class="card"><div class="toolbar"><select id="spSymptom"></select><button class="primary" id="spLocate">Wskaż sektor startowy</button></div><div id="spAdvice" class="result">Wybierz objaw i użyj przycisku, aby rozpocząć zawężanie usterki.</div></div><div id="spWarning"></div><div id="spContent"></div><div id="spDetail"></div>';

$('spDevice').innerHTML=Object.entries(DEV).map(([k,v])=>'<option value="'+k+'">'+v.icon+' '+esc(v.name)+'</option>').join('');
$('spState').innerHTML=STATE_NAMES.map((x,i)=>'<option value="'+i+'">'+(i+1)+'. '+esc(x)+'</option>').join('');
$('spState').value='3';
$('spSymptom').innerHTML=SYM.map(x=>'<option value="'+x[0]+'">Objaw: '+esc(x[1])+'</option>').join('');

function position(i){return i<4?{x:35+i*235,y:55}:{x:35+(7-i)*235,y:255}}
function pathBetween(a,b){if(a.y===b.y){const ay=a.y+65;if(b.x>a.x)return 'M '+(a.x+190)+' '+ay+' L '+b.x+' '+ay;return 'M '+a.x+' '+ay+' L '+(b.x+190)+' '+ay}const ax=a.x+95,bx=b.x+95,ay=a.y+130,by=b.y,mid=(ay+by)/2;return 'M '+ax+' '+ay+' L '+ax+' '+mid+' L '+bx+' '+mid+' L '+bx+' '+by}
function svg(d){
 const arrows=d.nodes.slice(0,-1).map((n,i)=>{const a=position(i),b=position(i+1),off=d.nodes[i+1].state>state;return '<path class="spArrow '+(off?'inactive':'')+'" d="'+pathBetween(a,b)+'"/>'}).join('');
 const nodes=d.nodes.map((n,i)=>{const p=position(i),status=n.state<=state?'active':n.state===state+1?'pending':'inactive';return '<g class="spNode '+status+(selected===n.id?' selected':'')+'" data-sp-node="'+n.id+'" tabindex="0" role="button" aria-label="'+esc(n.title)+'"><rect x="'+p.x+'" y="'+p.y+'" width="190" height="130" rx="16" fill="'+n.color+'" stroke="'+(n.state<=state?'#74e0a5':'#46647d')+'"/><circle cx="'+(p.x+22)+'" cy="'+(p.y+22)+'" r="14" fill="#071522"/><text x="'+(p.x+22)+'" y="'+(p.y+27)+'" text-anchor="middle" class="spNodeTitle">'+(i+1)+'</text><text x="'+(p.x+95)+'" y="'+(p.y+55)+'" text-anchor="middle" class="spNodeTitle">'+esc(n.title)+'</text><text x="'+(p.x+95)+'" y="'+(p.y+80)+'" text-anchor="middle" class="spNodeSub">'+esc(n.sub)+'</text><text x="'+(p.x+95)+'" y="'+(p.y+106)+'" text-anchor="middle" class="spNodeSub">'+(n.state<=state?'● AKTYWNY':'○ OCZEKUJE')+'</text></g>'}).join('');
 return '<div class="spDiagramWrap"><svg class="spDiagram" viewBox="0 0 1000 455" role="img" aria-label="Graficzna sekwencja zasilania"><defs><marker id="spArrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#73bdfb"/></marker></defs>'+arrows+nodes+'</svg></div><div class="spLegend"><span><i style="background:#2e8157"></i>sektor powinien pracować</span><span><i style="background:#506071"></i>kolejny etap</span><span><i style="background:#26313c"></i>jeszcze nieaktywny</span></div><div class="spStepList">'+d.nodes.map((n,i)=>'<div class="spStep '+(n.state<=state?'active':'')+(selected===n.id?' selected':'')+'" data-sp-node="'+n.id+'"><div class="spNum">'+(i+1)+'</div><b>'+esc(n.title)+'</b><div class="muted small">'+esc(d.states[n.state])+'</div></div>').join('')+'</div>'}
function table(d){return '<div class="card"><h2>Kolejność uruchamiania</h2><div style="overflow:auto"><table class="spSeqTable"><thead><tr><th>Krok</th><th>Sektor</th><th>Stan</th><th>Wejście</th><th>Wyjście</th><th>Warunek przejścia</th></tr></thead><tbody>'+d.nodes.map((n,i)=>'<tr data-sp-node="'+n.id+'" style="cursor:pointer"><td><b>'+(i+1)+'</b></td><td><b>'+esc(n.title)+'</b><br><span class="muted small">'+esc(n.sub)+'</span></td><td><span class="spStateBadge spState'+n.state+'">'+esc(STATE_NAMES[n.state])+'</span></td><td>'+esc(n.input)+'</td><td>'+esc(n.output)+'</td><td>'+esc(n.enable)+'</td></tr>').join('')+'</tbody></table></div></div>'}
function rails(d){return '<div class="card"><h2>Tory zasilania i sygnały kontrolne</h2><p class="muted">Czytaj od góry: wejście sektora → przetwarzanie → wyjście → warunek uruchomienia następnego bloku.</p><div class="spPowerTree">'+d.nodes.map((n,i)=>'<div class="spRail" data-sp-node="'+n.id+'" style="cursor:pointer;border-left-color:'+n.color+'"><b>'+(i+1)+'. '+esc(n.title)+'</b><p class="small"><b>WE:</b> '+esc(n.input)+'</p><p class="small"><b>WY:</b> '+esc(n.output)+'</p><p class="small"><b>CTRL:</b> '+esc(n.enable)+'</p></div>').join('')+'</div></div>'}
function render(){const d=DEV[current];$('spWarning').innerHTML='<div class="danger"><b>⚠️ Bezpieczeństwo:</b> '+esc(d.warning)+'</div>';$('spContent').innerHTML=mode==='map'?svg(d):mode==='sequence'?table(d):rails(d);bindNodes();if(selected&&!d.nodes.some(x=>x.id===selected))selected=null;if(selected)detail(selected);else $('spDetail').innerHTML=''}
function bindNodes(){document.querySelectorAll('[data-sp-node]').forEach(el=>{el.onclick=()=>{selected=el.dataset.spNode;render()};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selected=el.dataset.spNode;render()}}})}
function detail(id){const d=DEV[current],n=d.nodes.find(x=>x.id===id),i=d.nodes.indexOf(n);if(!n)return;$('spDetail').innerHTML='<div class="detailBox"><div class="toolbar"><button class="secondary" id="spPrev" '+(i===0?'disabled':'')+'>← Poprzedni sektor</button><button class="secondary" id="spNext" '+(i===d.nodes.length-1?'disabled':'')+'>Następny sektor →</button></div><span class="badge">Sektor '+(i+1)+' / '+d.nodes.length+'</span><span class="spStateBadge spState'+n.state+'">'+esc(STATE_NAMES[n.state])+'</span><h1 style="margin-top:10px">'+esc(n.title)+'</h1><p class="muted">'+esc(n.sub)+'</p><div class="spDetailGrid"><div class="spInfo"><h3>➡️ Wejście sektora</h3><p>'+esc(n.input)+'</p></div><div class="spInfo"><h3>⬅️ Wyjście sektora</h3><p>'+esc(n.output)+'</p></div><div class="spInfo"><h3>🔑 Sygnały sterujące</h3><p>'+esc(n.enable)+'</p></div><div class="spInfo"><h3>🧩 Typowe elementy</h3><p>'+esc(n.parts)+'</p></div><div class="spInfo"><h3>📏 Co mierzyć</h3><p>'+esc(n.measure)+'</p></div><div class="spInfo"><h3>⚠️ Typowe objawy</h3><p>'+esc(n.symptom)+'</p></div></div><div class="result"><b>Decyzja diagnostyczna</b><br>'+esc(n.next)+'</div><div class="note" style="margin-top:10px"><b>Zasada granicy sektorów:</b> jeśli wejście tego bloku jest prawidłowe, warunek EN został spełniony, a wyjścia brak lub jest niestabilne — usterki szukaj w tym sektorze albo w jego obciążeniu.</div></div>';$('spPrev').onclick=()=>{if(i>0){selected=d.nodes[i-1].id;render()}};$('spNext').onclick=()=>{if(i<d.nodes.length-1){selected=d.nodes[i+1].id;render()}};$('spDetail').scrollIntoView({behavior:'smooth',block:'nearest'})}
function locate(){const d=DEV[current],key=$('spSymptom').value,id=d.sym[key],n=d.nodes.find(x=>x.id===id),i=d.nodes.indexOf(n);selected=id;state=Math.max(state,n.state);$('spState').value=String(state);$('spAdvice').innerHTML='<b>Zacznij od sektora '+(i+1)+': '+esc(n.title)+'</b><br>'+esc(n.next)+'<br><span class="muted small">Najpierw potwierdź prawidłowe wejście poprzedniego sektora — wskazanie jest punktem startowym, nie gotową diagnozą.</span>';render()}
$('spDevice').onchange=()=>{current=$('spDevice').value;selected=null;render()};$('spState').onchange=()=>{state=+$('spState').value;render()};$('spMode').onchange=()=>{mode=$('spMode').value;render()};$('spLocate').onclick=locate;
render();
})();
