(function(){
'use strict';
const $=id=>document.getElementById(id);
if(!$('bsDevice')) return;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

const DEVICES={
 tv:{name:'Telewizor LED/LCD',icon:'📺',danger:'W zasilaczu TV występuje 230 V AC, około 325 V DC, a przy PFC zwykle około 380–400 V DC. Jeśli nie masz przygotowania do pracy przy napięciu sieciowym, ogranicz się do oględzin i strony niskonapięciowej po odłączeniu zasilania.',
  start:'Ustal, czy uszkodzenie dotyczy zasilacza, płyty MAIN, T-CON/panelu, podświetlenia czy audio. Najpierw zmierz STBY, potem obserwuj PS_ON i BL_ON.',
  flow:['230 V / bezpiecznik','PSU + STBY','PS_ON / szyny robocze','MAIN / SoC','T-CON / panel','LED / audio'],
  sectors:[
   {id:'input',n:'Wejście sieciowe i filtr',c:'#dc5a63',where:'Przy gnieździe 230 V: bezpiecznik, MOV, NTC, filtr EMI, mostek prostowniczy i duży kondensator.',parts:'F, MOV, NTC, mostek BR, kondensator 400–450 V',measure:'Bez zasilania: bezpiecznik, zwarcie mostka i MOSFET-a. Pod napięciem wyłącznie bezpiecznie: około 310–325 V DC na kondensatorze bez PFC.',sym:'Całkowicie martwy TV, przepalony bezpiecznik, cykanie lub ponowne przepalanie.',next:'Jeśli bezpiecznik jest przerwany, nie wymieniaj go w ciemno. Szukaj zwarcia w mostku, MOSFET-cie i stronie pierwotnej.'},
   {id:'psu',n:'Zasilacz STBY / PFC / główne wyjścia',c:'#f0a243',where:'Płyta zasilacza; transformatory, duże cewki, kondensatory i złącze do MAIN.',parts:'PWM, MOSFET, transoptor, TL431, PFC, prostowniki wtórne',measure:'Najpierw STBY 3,3 V lub 5 V. Po PS_ON sprawdź 12/13/24 V według opisu na złączu. Oscyloskopem oceń tętnienia.',sym:'Brak diody STBY, TV próbuje startować, pulsują napięcia, restartuje się.',next:'STBY prawidłowe? Przejdź do MAIN i PS_ON. STBY brak lub pulsuje? Zostań w PSU i sprawdź obciążenie wyjścia.'},
   {id:'main',n:'Płyta MAIN – procesor i zasilania',c:'#4ba3e3',where:'Płyta z HDMI, tunerem, USB i procesorem pod radiatorem.',parts:'SoC, eMMC/NAND, DDR, buck/LDO 5/3,3/1,8/1,2/~1,0 V',measure:'Sprawdź wejście z PSU, wszystkie cewki przetwornic, RESET, zegar i aktywność eMMC. Zacznij od szyny, której brakuje.',sym:'Dioda reaguje, ale brak startu; logo i restart; brak HDMI, tunera, menu lub sterowania.',next:'Brak PS_ON mimo dobrego STBY kieruje na MAIN. PS_ON jest, lecz brak jednej szyny lokalnej – sprawdź jej przetwornicę i obciążenie.'},
   {id:'tcon',n:'T-CON i panel',c:'#9a76e8',where:'Mała płyta pod metalową osłoną przy matrycy albo układ zintegrowany z panelem.',parts:'Bezpiecznik SMD, DC/DC, gamma, level shifter, taśmy COF',measure:'Sprawdź bezpiecznik i wejście często 12 V. Potem AVDD, VGH, VGL i VCOM wyłącznie według dokumentacji panelu.',sym:'Podświetlenie jest, ale brak treści; biały ekran; połowa obrazu; pasy i negatyw.',next:'Jest sygnał LVDS/eDP i napięcia T-CON, ale obraz wadliwy? Porównaj połówki panelu i taśmy. Nie podawaj obcych napięć na panel.'},
   {id:'backlight',n:'Driver LED i podświetlenie',c:'#e6ce46',where:'Na PSU lub oddzielnej płycie; złącze przewodów idących do listew LED.',parts:'Sterownik LED, MOSFET, cewka/transformator, diody, listwy LED',measure:'Sprawdź BL_ON/PWM, napięcie wyjściowe drivera i testerem LED poszczególne listwy po odłączeniu.',sym:'Dźwięk jest, obraz widać pod latarką; mignie logo i gaśnie; nierówne podświetlenie.',next:'BL_ON jest, driver próbuje podnieść napięcie i wyłącza się – podejrzewaj przerwę/listwę LED. BL_ON brak – wróć do MAIN.'},
   {id:'audio',n:'Audio i wzmacniacz',c:'#4bc39a',where:'W okolicy złączy głośników; zwykle układ wzmacniacza z kondensatorami i dławikami.',parts:'Audio codec, końcówka klasy D, 12/24 V, głośniki',measure:'Zasilanie końcówki, MUTE/ENABLE, obecność sygnału wejściowego i wyjścia na oba kanały.',sym:'Obraz prawidłowy, brak dźwięku, jeden kanał, trzaski lub wyłączanie.',next:'Sygnał dochodzi do wzmacniacza, ale wyjścia brak – sprawdź MUTE, zwarcie głośnika i końcówkę mocy.'}
  ]},
 phone:{name:'Telefon',icon:'📱',danger:'Odłącz baterię przed pomiarem rezystancji i lutowaniem. Nie wstrzykuj napięcia bez ustalenia nominalnej wartości szyny; szyny rdzenia mogą mieć naturalnie bardzo niską rezystancję.',
  start:'Najpierw ustal reakcję na USB i pobór prądu. Oddziel usterkę wejścia ładowania, baterii, PMIC, szyn startowych, SoC/pamięci i peryferiów.',
  flow:['USB-C / bateria','ESD / OVP / charger','PMIC + ALW','SoC / RAM','UFS/eMMC','ekran / RF / audio'],
  sectors:[
   {id:'usb',n:'Port USB-C i ochrona',c:'#e06a63',where:'Dolna płytka lub krawędź płyty: port, ESD, filtry, CC1/CC2, OVP.',parts:'USB-C, TVS/ESD, filtry, układ OVP, linie CC',measure:'Sprawdź mechanikę portu, VBUS 5 V, rezystancję VBUS do GND bez zasilania, CC1/CC2 i przejście do chargera.',sym:'Brak reakcji na przewód, ładowanie tylko pod kątem, brak danych, komunikat wilgoci.',next:'5 V jest na porcie, ale nie za OVP – sektor wejścia. 5 V dochodzi do chargera – przejdź do charger/baterii.'},
   {id:'battery',n:'Bateria i ładowanie',c:'#eaa741',where:'Złącze baterii oraz układ charger/power-path z MOSFET-ami i rezystorem pomiarowym.',parts:'VBAT, NTC/ID, charger IC, power-path, shunt',measure:'Napięcie baterii pod obciążeniem, NTC/ID, VBAT na płycie, prąd ładowania oraz sygnały I²C chargera.',sym:'Nie ładuje, pokazuje 0/1%, wyłącza się pod obciążeniem, grzeje układ ładowania.',next:'Sprawna bateria i VBUS obecne, ale brak VBAT/system – sprawdź charger i power-path. VBAT jest – przejdź do PMIC.'},
   {id:'pmic',n:'PMIC i szyny always-on',c:'#4e9fe1',where:'Zwykle blisko SoC; kilka cewek i kondensatorów otaczających układ zarządzania zasilaniem.',parts:'PMIC, buck/LDO, cewki, zegar 32 kHz, reset',measure:'Test diody/opór na cewkach bez zasilania; podczas startu szukaj szyn 1,8/2,8/3,0 V i dynamicznych szyn rdzenia.',sym:'Brak startu, stały niski pobór, zwarcie głównej szyny, szybkie grzanie.',next:'Najpierw wskaż szynę o nieprawidłowej rezystancji lub brakującym napięciu. Dopiero potem lokalizuj element termicznie.'},
   {id:'soc',n:'SoC, RAM i zegary',c:'#9b72de',where:'Centralny ekranowany sektor; procesor często ma RAM w układzie PoP.',parts:'SoC/AP, RAM, oscylatory, reset, magistrale',measure:'Sekwencja poboru prądu, szyny rdzenia, RESET i zegary. Oscyloskopem sprawdź aktywność, nie mierz linii szybkich przypadkową sondą.',sym:'Pobór zatrzymuje się na powtarzalnej wartości, restarty, brak pełnego bootu.',next:'Jeśli wszystkie zasilania i zegary są poprawne, sprawdź pamięć/oprogramowanie i komunikację. Nie wymieniaj SoC na podstawie samego grzania.'},
   {id:'memory',n:'Pamięć UFS / eMMC / NAND',c:'#52b78d',where:'Blisko SoC, zwykle układ BGA zasilany kilkoma napięciami.',parts:'UFS/eMMC/NAND, VCC, VCCQ, CLK, RESET',measure:'Sprawdź VCC/VCCQ, reset i aktywność zegara/danych podczas próby startu. Użyj odpowiednich narzędzi serwisowych.',sym:'Logo i restart, tryb recovery, brak pamięci, zatrzymanie startu po prawidłowej sekwencji PMIC.',next:'Brak jednej szyny pamięci – napraw jej zasilanie. Szyny i aktywność są, ale odczyt nie działa – podejrzenie pamięci lub danych.'},
   {id:'periph',n:'Wyświetlacz, RF, audio i kamery',c:'#e1cf4a',where:'Sektory przy złączach FPC i przewodach antenowych, zwykle przy krawędziach płyty.',parts:'FPC LCD, boost podświetlenia, PA/RF, codec, kamery',measure:'Sprawdź złącza, filtry, zabezpieczenia ESD, zasilania danego modułu i próbę ze sprawnym modułem.',sym:'Telefon startuje, lecz brak obrazu/dotyku/zasięgu/dźwięku/kamery.',next:'Gdy system działa, nie wracaj od razu do PMIC. Zawęź usterkę do jednej funkcji, złącza i jej lokalnych szyn.'}
  ]},
 laptop:{name:'Laptop',icon:'💻',danger:'Przed pomiarami bez zasilania odłącz ładowarkę i baterię główną. Podczas wstrzykiwania napięcia zacznij od bardzo niskiego napięcia i ograniczenia prądu zgodnego z badaną szyną.',
  start:'Podziel płytę według sekwencji: wejście 19–20 V → charger → 3/5 V ALW → EC/KBC → S5/S3/S0 → CPU/RAM → BIOS i peryferia.',
  flow:['DC-IN / USB-C PD','MOSFET + charger','3V/5V ALW','EC/KBC + BIOS','S3/S0 / VRM','CPU / RAM / GPU'],
  sectors:[
   {id:'dcin',n:'Wejście DC / USB-C PD',c:'#db655f',where:'Przy gnieździe zasilania: bezpiecznik, TVS, MOSFET-y wejściowe, kontroler USB-C.',parts:'DC jack/USB-C, TVS, MOSFET ACFET/RBFET, rezystor pomiarowy',measure:'Napięcie przed i za MOSFET-ami, bramki MOSFET, sygnały ACDET/ACOK lub negocjacja USB-C PD.',sym:'0 A z zasilacza, brak diody ładowania, napięcie nie przechodzi na płytę.',next:'Napięcie przed MOSFET-em jest, za nim brak – sprawdź zwarcie, sterowanie bramką i charger. Nie zwieraj D-S na próbę.'},
   {id:'charger',n:'Charger i główna szyna systemowa',c:'#eea33e',where:'Blisko wejścia i złącza baterii; układ charger, MOSFET-y, cewka i shunt.',parts:'Charger IC, BATFET, shunt, B+, BQ/ISL/Richtek',measure:'VIN, ACOK, napięcie głównej szyny, wykrycie baterii, prąd ładowania i SMBus.',sym:'Działa tylko z baterii albo tylko z zasilacza, nie ładuje, pulsuje pobór.',next:'Główna szyna stabilna – przejdź do ALW. Niestabilna – odłącz baterię i sprawdź charger, MOSFET-y i obciążenie.'},
   {id:'alw',n:'Przetwornice 3 V / 5 V ALW',c:'#4c9edb',where:'Dwie większe cewki z kontrolerem PWM, zwykle w pobliżu EC/KBC.',parts:'PWM 3/5 V, MOSFET/DrMOS, cewki, LDO always-on',measure:'Rezystancja cewek do GND, VIN, EN, 3,3 V i 5 V, PGOOD. Sprawdź oba kanały osobno.',sym:'Laptop całkiem martwy mimo 19 V, brak reakcji POWER, grzanie zasilacza 3/5 V.',next:'Brak EN – cofnij się do sygnałów chargera/EC. EN jest, wyjścia brak – sprawdź PWM, MOSFET-y i zwarcie na szynie.'},
   {id:'ecbios',n:'EC/KBC, przycisk i BIOS',c:'#9b73df',where:'EC/KBC blisko klawiatury oraz mała pamięć SPI BIOS 8-pin.',parts:'EC/KBC, SPI BIOS, przycisk POWER, RTC, RESET',measure:'3,3 V na EC i BIOS, przycisk POWER, RSMRST#, sygnały zegara i aktywność SPI po wciśnięciu.',sym:'ALW są, lecz brak reakcji; włącza się bez obrazu; pętla startowa po aktualizacji.',next:'Brak aktywności EC/BIOS mimo zasilania – sprawdź reset, RTC, firmware i sam układ. Aktywność jest – śledź sekwencję SLP.'},
   {id:'vrm',n:'Sekwencja S3/S0 i VRM',c:'#e0cb48',where:'Przetwornice wokół CPU/GPU i RAM, liczne cewki oraz układy DrMOS.',parts:'VCORE, VCCSA, VCCIO, RAM, GPU VRM',measure:'Sygnały SLP_S3#/SLP_S4#, EN/PGOOD kolejnych przetwornic i napięcia na cewkach podczas startu.',sym:'Startuje i gaśnie, pobór rośnie na chwilę, wentylator drgnie, brak obrazu.',next:'Znajdź pierwszą szynę, która nie powstaje. Sprawdź, czy brakuje EN, czy przetwornica próbuje i wyłącza się.'},
   {id:'cpu',n:'CPU, RAM, GPU i obraz',c:'#51b58a',where:'Centralna część płyty: CPU/GPU pod chłodzeniem, sloty RAM, wyjścia obrazu.',parts:'CPU/PCH, RAM, GPU, eDP/HDMI, clock generator',measure:'Napięcia RAM, VCORE, zegary, reset, termikę, próbę z jedną pamięcią i zewnętrznym ekranem.',sym:'Płyta pozostaje włączona bez obrazu, kody RAM, artefakty, zawieszanie pod obciążeniem.',next:'Najpierw RAM/BIOS/ekran i sygnały startowe. Reflow nie jest diagnozą i może pogorszyć płytę.'}
  ]},
 pc:{name:'Komputer stacjonarny',icon:'🖥️',danger:'Zasilacza ATX nie otwieraj bez przygotowania do pracy po stronie sieciowej. Na płycie odłącz ATX/EPS i rozładuj ją przed pomiarem rezystancji.',
  start:'Oddziel problem ATX, standby, logiki włączenia, VRM CPU, RAM/BIOS i peryferiów. Pomocne są kody POST, diody diagnostyczne i głośniczek.',
  flow:['ATX 5VSB','PS_ON#','12/5/3,3 V','VRM CPU','BIOS / PCH','RAM / PCIe / I/O'],
  sectors:[
   {id:'atx',n:'Złącza ATX/EPS i standby',c:'#df655e',where:'24-pin ATX i 4/8-pin EPS przy krawędziach płyty.',parts:'5VSB, PS_ON#, PWR_OK, 12/5/3,3 V, bezpieczniki',measure:'5VSB przed startem, zwarcia głównych szyn bez zasilania, PS_ON# po POWER i napięcia pod obciążeniem.',sym:'Brak reakcji, rusza tylko na moment, resetuje się po podłączeniu EPS.',next:'5VSB brak – sprawdź PSU. 5VSB jest, PS_ON nie zmienia stanu – sektor logiki POWER/Super I/O.'},
   {id:'sio',n:'Super I/O i logika POWER',c:'#efa33f',where:'Układ wielopinowy blisko dolnej części płyty, BIOS-u i złącza panelu przedniego.',parts:'Super I/O, PWRBTN#, reset, zegar 32 kHz, standby LDO',measure:'Przycisk PWRBTN#, zasilanie SIO, reset, kwarc 32 kHz i reakcję PS_ON#.',sym:'5VSB prawidłowe, ale płyta nie uruchamia ATX lub uruchamia sama.',next:'PWRBTN dochodzi, lecz PS_ON brak – sprawdź SIO, BIOS/ME i warunki startowe.'},
   {id:'vrm',n:'VRM procesora',c:'#4b9edc',where:'Rząd cewek, MOSFET-ów/DrMOS i kondensatorów wokół gniazda CPU.',parts:'PWM, DrMOS, VCORE, SoC/SA, EPS 12 V',measure:'12 V EPS, zwarcie faz, PWM/EN, VCORE podczas startu i PGOOD. Porównaj temperatury faz.',sym:'Start i natychmiast stop, brak VCORE, mocne grzanie fazy, restart pod obciążeniem.',next:'PWM nie dostaje EN – szukaj wcześniej w sekwencji. EN jest i brak VCORE – badaj PWM/DrMOS/obciążenie.'},
   {id:'biospch',n:'BIOS, PCH/chipset i zegary',c:'#9b73df',where:'Pamięć SPI 8-pin oraz chipset pod radiatorem lub sam CPU w nowszych platformach.',parts:'SPI BIOS, PCH, RTC, generator zegara, ME/firmware',measure:'3,3/1,8 V BIOS, CS/CLK/DATA podczas startu, bateria RTC, zegary i reset platformy.',sym:'Wentylatory pracują, brak POST; restart po kilku sekundach; problem po aktualizacji BIOS.',next:'Brak odczytu BIOS – sprawdź zasilanie/reset/firmware. Odczyt jest, ale POST staje – użyj kodów POST i sprawdź RAM/CPU.'},
   {id:'ram',n:'RAM i sloty DIMM',c:'#52b78a',where:'Długie sloty DIMM obok procesora, terminatory i lokalne zasilania.',parts:'VDD/VDDQ, VPP, SPD, sloty, linie pamięci',measure:'Napięcia zgodne z generacją DDR, zasilanie SPD, próbę jednego modułu i kontrolę pinów socketu CPU.',sym:'Dioda DRAM, seria beepów, brak POST, niestabilność i błędy pamięci.',next:'Sprawny moduł nie działa w jednym kanale – sprawdź socket CPU, slot, terminatory i ścieżki.'},
   {id:'io',n:'PCIe, USB, LAN, audio i obraz',c:'#e0cc4a',where:'Sektory przy złączach zewnętrznych i slotach rozszerzeń.',parts:'PCIe, USB ESD, LAN PHY, audio codec, HDMI/DP',measure:'Lokalne bezpieczniki, 3,3/5/12 V, zegary PCIe, reset urządzenia i test z minimalną konfiguracją.',sym:'Komputer przechodzi POST, ale nie działa wybrany port, karta, dźwięk lub sieć.',next:'Jeśli POST jest prawidłowy, zawężaj do jednej magistrali i jej zasilania; nie wracaj do VRM CPU bez objawów.'}
  ]},
 tablet:{name:'Tablet',icon:'▣',danger:'Zasady jak w telefonie: odłącz baterię przed pracą bez zasilania, zachowaj ostrożność przy Li-ion i nie podawaj napięcia na nieznaną szynę.',
  start:'Tablet łączy architekturę telefonu z większym ekranem. Najczęściej rozdzielaj: port, charger/bateria, PMIC, SoC/pamięć, LCD/touch/backlight oraz łączność.',
  flow:['USB-C / Lightning','charger + bateria','PMIC / szyny','SoC / RAM / pamięć','LCD / touch / LED','Wi‑Fi / audio / kamery'],
  sectors:[
   {id:'port',n:'Port i wejście zasilania',c:'#df665e',where:'Przy dolnej krawędzi lub na osobnym flexie: port, ESD i filtry.',parts:'USB-C/Lightning, ESD, CC/USB, bezpiecznik',measure:'VBUS, rezystancja do GND, linie CC/identyfikacji i ciągłość flexu.',sym:'Brak ładowania i komunikacji, ładowanie pod kątem, przerwany port.',next:'VBUS nie opuszcza sektora portu – napraw wejście. Dochodzi do chargera – badaj power-path.'},
   {id:'charge',n:'Charger, bateria i power-path',c:'#efa341',where:'Przy złączu baterii; często osobny układ ładowania i duże kondensatory.',parts:'Charger, VBAT, NTC/ID, fuel gauge, MOSFET',measure:'Napięcie baterii, NTC, VBAT/SYS, pobór z USB i ładowanie pod obciążeniem.',sym:'Pokazuje ładowanie bez przyrostu, wyłącza się, 1%, brak pracy z baterii.',next:'SYS/VBAT prawidłowe – przejdź do PMIC. Brak – sprawdź charger, złącze i baterię.'},
   {id:'pmic',n:'PMIC i zasilania płyty',c:'#4b9edc',where:'W centrum płyty blisko procesora, otoczony cewkami i kondensatorami.',parts:'Buck/LDO, szyny ALW i rdzenia, zegary, reset',measure:'Opór/test diody cewek, szyny zawsze obecne i kolejność pojawiania się napięć po POWER.',sym:'Brak startu, zatrzymany pobór, grzejący element, restarty.',next:'Wskaż konkretną brakującą lub zwartą szynę, potem odłączaj jej odbiorniki i lokalizuj termicznie.'},
   {id:'socmem',n:'SoC, RAM i pamięć',c:'#9b73df',where:'Główny ekranowany obszar logic board.',parts:'SoC, RAM PoP, eMMC/UFS/NAND, oscylatory',measure:'Szyny rdzenia, reset, zegary, aktywność pamięci i zachowanie poboru podczas bootu.',sym:'Logo i restart, brak systemu, komputer wykrywa tryb awaryjny.',next:'Zasilania poprawne – sprawdź firmware i pamięć. Nie diagnozuj BGA na podstawie samego objawu.'},
   {id:'display',n:'LCD, dotyk i podświetlenie',c:'#e0cc4a',where:'Przy szerokich złączach FPC ekranu i digitizera; boost LED w pobliżu cewki.',parts:'FPC, filtry, touch IC, boost LED, bezpieczniki',measure:'Zasilania LCD/touch, ciągłość filtrów, sygnał enable i napięcie boost według modelu.',sym:'Tablet działa, ale brak obrazu/dotyku; ekran świeci bez treści; migocze.',next:'Najpierw test ze sprawnym modułem i kontrola złącza. Brak lokalnej szyny kieruje na sektor display, nie na SoC.'},
   {id:'periph',n:'Wi‑Fi, audio, kamery i czujniki',c:'#52b78a',where:'Przy antenach, głośnikach i złączach kamer na obrzeżu płyty.',parts:'Wi‑Fi/BT, codec, wzmacniacz, kamera, sensory',measure:'Lokalne zasilania, zegary, złącza, filtry ESD i próbę odłączenia wadliwego modułu.',sym:'System działa, lecz brakuje jednej funkcji albo restartuje po podłączeniu modułu.',next:'Odłącz podejrzany moduł i obserwuj, czy zwarcie/boot wraca do normy. Kontroluj złącze pod mikroskopem.'}
  ]}
};

function boardSvg(dev){
 const d=DEVICES[dev], horizontal=dev==='tv'||dev==='laptop'||dev==='pc';
 const w=horizontal?900:620,h=horizontal?430:720;
 const layout=horizontal
  ?[[55,70,220,125],[315,55,235,145],[600,65,240,125],[75,255,220,110],[345,250,210,120],[610,245,220,125]]
  :[[75,45,470,92],[55,170,235,145],[330,170,235,145],[55,360,235,145],[330,360,235,145],[75,555,470,100]];
 let comps='';
 for(let i=0;i<18;i++){const x=35+(i*83)%Math.max(300,w-100),y=25+(i*59)%Math.max(200,h-70);comps+='<rect x="'+x+'" y="'+y+'" width="'+(22+(i%4)*7)+'" height="'+(12+(i%3)*6)+'" rx="3" fill="#b9c3ad" opacity=".65"/><circle cx="'+(x+48)+'" cy="'+(y+14)+'" r="'+(5+i%5)+'" fill="#26312a" stroke="#91a184"/>';}
 const sectors=d.sectors.map((s,i)=>{const p=layout[i];return '<g class="bsHot" data-sector="'+s.id+'" tabindex="0" role="button"><rect x="'+p[0]+'" y="'+p[1]+'" width="'+p[2]+'" height="'+p[3]+'" rx="15" fill="'+s.c+'" fill-opacity=".28" stroke="'+s.c+'" stroke-width="4"/><circle cx="'+(p[0]+22)+'" cy="'+(p[1]+22)+'" r="15" fill="'+s.c+'"/><text x="'+(p[0]+22)+'" y="'+(p[1]+28)+'" text-anchor="middle" fill="#07111a" font-size="17" font-weight="900">'+(i+1)+'</text><text x="'+(p[0]+45)+'" y="'+(p[1]+28)+'" fill="#fff" font-size="17" font-weight="800">'+esc(s.n.length>27?s.n.slice(0,27)+'…':s.n)+'</text></g>';}).join('');
 return '<svg class="bsBoard" viewBox="0 0 '+w+' '+h+'" role="img" aria-label="Zdjęcie poglądowe płyty: '+esc(d.name)+' z zaznaczonymi sektorami"><defs><linearGradient id="pcb-'+dev+'" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#255c43"/><stop offset="1" stop-color="#102f27"/></linearGradient><filter id="shadow-'+dev+'"><feDropShadow dx="0" dy="8" stdDeviation="8" flood-opacity=".5"/></filter></defs><rect width="'+w+'" height="'+h+'" rx="28" fill="#17232c"/><g filter="url(#shadow-'+dev+')"><path d="M25 28H'+(w-25)+'V'+(h-28)+'H25Z" fill="url(#pcb-'+dev+')" stroke="#789985" stroke-width="5"/>'+comps+'<path d="M40 '+(h-45)+'H'+(w-40)+'M55 45V'+(h-55)+'" stroke="#81a184" stroke-opacity=".28" stroke-width="3"/></g>'+sectors+'</svg>';
}

function renderDevice(){
 const key=$('bsDevice').value,d=DEVICES[key];
 $('bsIntro').innerHTML='<div class="moduleHero"><span class="badge">'+d.icon+' '+esc(d.name)+'</span><h2>Jak podzielić płytę na sektory</h2><p>'+esc(d.start)+'</p><div class="flow">'+d.flow.map((v,i)=>'<span><b>'+(i+1)+'</b> '+esc(v)+'</span>').join('')+'</div></div><div class="danger"><b>⚠️ Bezpieczeństwo</b><br>'+esc(d.danger)+'</div>';
 $('bsBoard').innerHTML='<div class="card"><h2>Zdjęcie poglądowe / mapa funkcjonalna</h2><p class="muted small">Dotknij kolorowego sektora albo wybierz go z listy. Rozmieszczenie jest typowe — na konkretnej płycie potwierdź je po złączach, cewkach, oznaczeniach i schemacie.</p>'+boardSvg(key)+'</div>';
 $('bsSectorList').innerHTML=d.sectors.map((s,i)=>'<button class="bsSectorBtn" data-sector="'+s.id+'"><span style="background:'+s.c+'">'+(i+1)+'</span><b>'+esc(s.n)+'</b></button>').join('');
 $('bsSectorDetail').innerHTML='<div class="card"><h2>Wybierz sektor na grafice</h2><p class="muted">Zobaczysz punkty rozpoznawcze, pomiary, objawy i decyzję, dokąd przejść dalej.</p></div>';
 const open=id=>openSector(key,id);
 document.querySelectorAll('#bsBoard [data-sector],#bsSectorList [data-sector]').forEach(x=>{x.onclick=()=>open(x.dataset.sector);x.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(x.dataset.sector);}}});
 renderWizard();
}

function openSector(dev,id){
 const d=DEVICES[dev],s=d.sectors.find(x=>x.id===id),i=d.sectors.indexOf(s);
 if(!s)return;
 document.querySelectorAll('.bsSectorBtn').forEach(x=>x.classList.toggle('active',x.dataset.sector===id));
 $('bsSectorDetail').innerHTML='<div class="detailBox"><span class="badge">Sektor '+(i+1)+'</span><h2>'+esc(s.n)+'</h2><div class="bsDetailGrid"><div class="bsInfo"><h3>📍 Jak rozpoznać</h3><p>'+esc(s.where)+'</p></div><div class="bsInfo"><h3>🧩 Typowe elementy</h3><p>'+esc(s.parts)+'</p></div><div class="bsInfo"><h3>📏 Co mierzyć</h3><p>'+esc(s.measure)+'</p></div><div class="bsInfo"><h3>⚠️ Objawy</h3><p>'+esc(s.sym)+'</p></div></div><div class="result"><b>Decyzja diagnostyczna</b><br>'+esc(s.next)+'</div><div class="note" style="margin-top:10px"><b>Zasada:</b> sektor uznaj za podejrzany dopiero, gdy na jego wejściu warunki są poprawne, a na wyjściu brakuje napięcia, sygnału lub reakcji. Zawsze wyklucz zwarcie w odbiorniku kolejnego sektora.</div></div>';
 $('bsSectorDetail').scrollIntoView({behavior:'smooth',block:'nearest'});
}

const WIZARD={
 dead:{name:'Urządzenie całkowicie martwe',steps:['Odłącz zasilanie. Oględziny: zalanie, pęknięcia, nadpalenia, brakujące elementy.','Zmierz rezystancję głównego wejścia do masy. Jeśli jest zwarcie, nie włączaj urządzenia.','Podaj prawidłowe zasilanie z ograniczeniem prądu i obserwuj pobór.','Sprawdź napięcie na wejściu pierwszego sektora oraz za zabezpieczeniem/MOSFET-em.','Sprawdź pierwsze napięcie standby/always-on.','Jeśli ALW jest prawidłowe, badaj przycisk POWER, reset, zegar i sygnały enable.'],result:'Pierwszy punkt, w którym prawidłowe wejście nie daje prawidłowego wyjścia, wyznacza podejrzany sektor.'},
 short:{name:'Zwarcie lub duży pobór',steps:['Bez zasilania porównaj opór/test diody głównych szyn do masy.','Ustal nominalne napięcie zwartej szyny ze schematu lub połączonych układów.','Odłącz możliwe podzespoły i zworki rozdzielające gałęzie.','Wstrzyknij napięcie niższe lub równe nominalnemu z małym ograniczeniem prądu.','Szukaj grzania kamerą termiczną, IPA lub sprayem zamrażającym.','Potwierdź winny element po odlutowaniu; grzejący IC może być tylko odbiornikiem zwarcia dalej.'],result:'Nie wstrzykuj napięcia w szynę CPU/GPU/SoC bez pewności wartości. Zacznij nisko i kontroluj temperaturę.'},
 boot:{name:'Uruchamia się, ale nie kończy startu',steps:['Zapisz sekwencję poboru prądu i czas do restartu.','Sprawdź wszystkie szyny ALW, potem szyny pojawiające się po POWER.','Znajdź pierwszą szynę bez PGOOD lub bez napięcia.','Sprawdź reset, zegary oraz aktywność pamięci BIOS/eMMC/UFS.','Odłącz peryferia mogące blokować magistralę lub powodować zwarcie.','Dopiero po potwierdzeniu hardware sprawdź firmware i zawartość pamięci.'],result:'Powtarzalny punkt zatrzymania zwykle odpowiada etapowi sekwencji zasilania, pamięci lub inicjalizacji peryferium.'},
 function:{name:'Nie działa tylko jedna funkcja',steps:['Potwierdź objaw i wyklucz ustawienia/oprogramowanie.','Zlokalizuj złącze tej funkcji i prześledź ścieżkę do filtra/ESD/układu sterującego.','Sprawdź lokalne bezpieczniki, zasilania i sygnał enable.','Obejrzyj złącze, pady i elementy ESD pod mikroskopem.','Jeśli możliwe, podłącz znany sprawny moduł.','Porównaj pomiary z identycznym kanałem lub sprawną płytą.'],result:'Przy sprawnym systemie głównym skup się na lokalnym sektorze funkcji, zamiast wymieniać PMIC lub procesor.'}
};

function renderWizard(){
 const k=$('bsSymptom').value,w=WIZARD[k];
 $('bsWizard').innerHTML='<div class="card"><h2>Procedura: '+esc(w.name)+'</h2>'+w.steps.map((s,i)=>'<label class="workCheck"><input type="checkbox"><span><b>'+(i+1)+'.</b> '+esc(s)+'</span></label>').join('')+'<div class="result"><b>Wniosek</b><br>'+esc(w.result)+'</div></div>';
}

$('bsDevice').addEventListener('change',renderDevice);
$('bsSymptom').addEventListener('change',renderWizard);
renderDevice();
})();
