(function(){
'use strict';
const $=id=>document.getElementById(id);
if(!$('formulasymbols')) return;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>Number(String(v??'').trim().replace(',','.'));
const ok=v=>Number.isFinite(v);
const fmt=(v,d=4)=>{if(!ok(v))return '—';const a=Math.abs(v);if(a!==0&&(a>=1e6||a<.001))return v.toExponential(3);return Number(v.toFixed(d)).toLocaleString('pl-PL')};

const DB=[
 {s:'U',name:'Napięcie elektryczne',cat:'Podstawowe',unit:'wolt [V]',formula:'U = I × R',desc:'Różnica potencjałów między dwoma punktami. Napięcie zawsze mierzymy pomiędzy punktami, np. względem masy.',example:'Dla I = 2 A i R = 6 Ω: U = 2 × 6 = 12 V.',use:'Pomiar szyn 5 V, 3,3 V i 1,8 V; sprawdzanie zasilacza, baterii i spadków napięcia.',tip:'U₂ oznacza po prostu napięcie opisane indeksem 2 — np. w drugim punkcie pomiarowym albo na drugim elemencie.'},
 {s:'I',name:'Natężenie prądu',cat:'Podstawowe',unit:'amper [A]',formula:'I = U / R',desc:'Ilość ładunku przepływającego w czasie. Amperomierz włącza się szeregowo, a zasilacz laboratoryjny może pokazać pobór całej płyty.',example:'Dla U₂ = 12 V i R = 6 Ω: I = 12 / 6 = 2 A.',use:'Analiza poboru płyty telefonu, dobór bezpiecznika, przewodu, tranzystora lub zasilacza.',tip:'Nie przykładaj miernika ustawionego na A bezpośrednio do napięcia — powstanie zwarcie.'},
 {s:'R',name:'Rezystancja',cat:'Podstawowe',unit:'om [Ω]',formula:'R = U / I',desc:'Miara przeciwstawiania się przepływowi prądu. Rezystancję mierzymy na układzie bez zasilania.',example:'Jeśli na elemencie jest 5 V i płynie 0,01 A, R = 5 / 0,01 = 500 Ω.',use:'Dobór rezystora LED, szukanie zwarcia, kontrola rezystorów pomiarowych i dzielników.',tip:'Niska rezystancja szyny CPU/GPU nie zawsze oznacza zwarcie. Porównuj z dokumentacją lub sprawną płytą.'},
 {s:'P',name:'Moc elektryczna',cat:'Moc i energia',unit:'wat [W]',formula:'P = U × I',desc:'Szybkość pobierania lub oddawania energii. Moc wydzielana w elemencie często zamienia się w ciepło.',example:'Urządzenie 12 V pobierające 2 A ma P = 12 × 2 = 24 W.',use:'Dobór mocy zasilacza, rezystora, przetwornicy, MOSFET-a i chłodzenia.',tip:'Dla rezystora użyjesz też P = I²R albo P = U²/R. Zostaw zapas mocy.'},
 {s:'E / W',name:'Energia / praca',cat:'Moc i energia',unit:'dżul [J], watogodzina [Wh]',formula:'E = P × t',desc:'Ilość energii zużytej lub zgromadzonej w określonym czasie.',example:'Akumulator oddający 20 W przez 3 h dostarcza 60 Wh.',use:'Ocena energii pakietu, czasu pracy urządzenia i zużycia energii.',tip:'1 Wh = 3600 J. W niektórych materiałach energię oznacza się E, a pracę W.'},
 {s:'Q',name:'Ładunek elektryczny',cat:'Podstawowe',unit:'kulomb [C], amperogodzina [Ah]',formula:'Q = I × t',desc:'Ilość ładunku elektrycznego. W bateriach praktycznie używa się Ah lub mAh.',example:'Prąd 2 A płynący przez 0,5 h daje Q = 1 Ah.',use:'Pojemność baterii i akumulatorów, obliczanie czasu rozładowania.',tip:'Ah opisuje ładunek, a Wh energię. Ta sama liczba Ah przy innym napięciu oznacza inną energię.'},
 {s:'C',name:'Pojemność elektryczna',cat:'Elementy i sygnały',unit:'farad [F]',formula:'C = Q / U',desc:'Zdolność kondensatora do zgromadzenia ładunku przy określonym napięciu.',example:'1000 µF = 0,001 F. Kondensator na 12 V musi mieć napięcie znamionowe wyższe niż napięcie pracy.',use:'Filtracja zasilania, podtrzymanie, układy czasowe i sprzęganie sygnałów.',tip:'Na schemacie C może być symbolem wielkości pojemności i oznaczeniem elementu, np. C127.'},
 {s:'L',name:'Indukcyjność',cat:'Elementy i sygnały',unit:'henr [H]',formula:'Xᴸ = 2πfL',desc:'Właściwość cewki opisująca magazynowanie energii w polu magnetycznym i reakcję na zmianę prądu.',example:'Dla L = 10 mH i f = 1 kHz: Xᴸ ≈ 62,83 Ω.',use:'Przetwornice impulsowe, filtry LC, dławiki i obwody rezonansowe.',tip:'L na PCB zwykle oznacza cewkę/dławik, np. L5. Niska rezystancja DC cewki mocy jest normalna.'},
 {s:'f',name:'Częstotliwość',cat:'Elementy i sygnały',unit:'herc [Hz]',formula:'f = 1 / T',desc:'Liczba pełnych okresów sygnału w jednej sekundzie.',example:'Jeżeli okres T = 20 ms = 0,02 s, f = 1 / 0,02 = 50 Hz.',use:'Pomiar zegarów, PWM, tętnień zasilacza, audio i komunikacji cyfrowej.',tip:'Przed obliczeniem zamień ms lub µs na sekundy.'},
 {s:'T',name:'Okres sygnału',cat:'Elementy i sygnały',unit:'sekunda [s]',formula:'T = 1 / f',desc:'Czas trwania jednego pełnego cyklu przebiegu okresowego.',example:'Dla f = 1 kHz: T = 1 / 1000 = 0,001 s = 1 ms.',use:'Ustawianie podstawy czasu oscyloskopu i analiza PWM.',tip:'Nie myl okresu T z temperaturą, która także bywa oznaczana literą T — znaczenie wynika z kontekstu.'},
 {s:'Z',name:'Impedancja',cat:'Prąd przemienny',unit:'om [Ω]',formula:'Z = U / I (AC)',desc:'Całkowity opór obwodu dla prądu przemiennego, obejmujący rezystancję i reaktancję.',example:'Jeśli przy sygnale AC 2 V płynie 0,25 A, moduł impedancji wynosi 8 Ω.',use:'Głośniki, filtry, transformatory, linie sygnałowe i obwody AC.',tip:'Impedancja zależy od częstotliwości; głośnik 8 Ω nie ma stałych 8 Ω dla każdej częstotliwości.'},
 {s:'Xᴄ',name:'Reaktancja pojemnościowa',cat:'Prąd przemienny',unit:'om [Ω]',formula:'Xᴄ = 1 / (2πfC)',desc:'Opór pozorny kondensatora dla prądu przemiennego. Maleje wraz ze wzrostem częstotliwości i pojemności.',example:'Dla 1 µF i 1 kHz: Xᴄ ≈ 159,15 Ω.',use:'Filtry, kondensatory sprzęgające, tłumienie tętnień i diagnostyka sygnałów AC.',tip:'W obliczeniu podaj C w faradach, np. 1 µF = 0,000001 F.'},
 {s:'Xᴸ',name:'Reaktancja indukcyjna',cat:'Prąd przemienny',unit:'om [Ω]',formula:'Xᴸ = 2πfL',desc:'Opór pozorny cewki dla prądu przemiennego. Rośnie z częstotliwością i indukcyjnością.',example:'Dla 10 mH i 1 kHz: Xᴸ ≈ 62,83 Ω.',use:'Dławiki, zwrotnice, filtry i przetwornice.',tip:'W obliczeniu podaj L w henrach, np. 10 mH = 0,01 H.'},
 {s:'η',name:'Sprawność',cat:'Moc i energia',unit:'procent [%]',formula:'η = (Pwy / Pwe) × 100%',desc:'Stosunek mocy użytecznej na wyjściu do mocy pobranej na wejściu.',example:'Przetwornica pobiera 50 W i oddaje 45 W: η = 45 / 50 × 100% = 90%.',use:'Ocena strat i grzania zasilaczy, ładowarek, wzmacniaczy i przetwornic.',tip:'Strata mocy w tym przykładzie wynosi 5 W i w większości zamieni się w ciepło.'},
 {s:'Δ',name:'Zmiana / różnica',cat:'Oznaczenia',unit:'zależna od wielkości',formula:'ΔU = U₂ − U₁',desc:'Grecka litera delta oznacza zmianę lub różnicę między dwiema wartościami.',example:'U₁ = 12,0 V, U₂ = 11,4 V, więc ΔU = −0,6 V; spadek ma wartość 0,6 V.',use:'Spadek napięcia na przewodzie, zmiana temperatury, rozjazd sekcji baterii.',tip:'Znak wyniku pokazuje kierunek zmiany; w praktyce często podaje się też wartość bezwzględną różnicy.'},
 {s:'Σ',name:'Suma',cat:'Oznaczenia',unit:'zależna od wielkości',formula:'RΣ = R₁ + R₂ + …',desc:'Grecka litera sigma oznacza sumowanie wielu wartości.',example:'Rezystory szeregowe 100 Ω, 220 Ω i 330 Ω: RΣ = 650 Ω.',use:'Sumowanie rezystancji, napięć sekcji baterii, mocy i energii.',tip:'W połączeniu szeregowym rezystancje się sumują; w równoległym obowiązuje odwrotność sumy odwrotności.'},
 {s:'GND / ⏚',name:'Masa układu',cat:'Oznaczenia',unit:'punkt odniesienia',formula:'U = Vpunkt − VGND',desc:'Umowny punkt odniesienia 0 V w danym obwodzie. Nie każda masa jest przewodem ochronnym PE.',example:'Pomiar 3,3 V: czarna sonda na GND, czerwona na badanym punkcie.',use:'Punkt odniesienia pomiarów na płytach i wspólna linia powrotna zasilania.',tip:'W urządzeniu sieciowym masa strony pierwotnej może być niebezpieczna i nieizolowana od sieci.'},
 {s:'DC / ⎓',name:'Prąd lub napięcie stałe',cat:'Oznaczenia',unit:'V DC, A DC',formula:'wartość o stałej polaryzacji',desc:'Napięcie lub prąd o niezmiennym kierunku; może zawierać tętnienia.',example:'Bateria ma około 3,7 V DC, a szyna USB około 5 V DC.',use:'Baterie, zasilacze laboratoryjne, szyny płyt głównych.',tip:'Do pomiaru baterii wybierz V⎓, nie V~.'},
 {s:'AC / ∿',name:'Prąd lub napięcie przemienne',cat:'Oznaczenia',unit:'V AC, A AC',formula:'wartość zmienia kierunek',desc:'Napięcie lub prąd zmieniający wartość i zwykle polaryzację w czasie.',example:'Sieć w Polsce ma nominalnie 230 V AC, 50 Hz.',use:'Sieć energetyczna, transformatory, sygnały audio i pomiar tętnień.',tip:'230 V AC jest niebezpieczne. Multimetr i sondy muszą mieć właściwą kategorię pomiarową.'},
 {s:'D / PWM',name:'Współczynnik wypełnienia',cat:'Elementy i sygnały',unit:'procent [%]',formula:'D = (tON / T) × 100%',desc:'Część okresu, przez którą sygnał PWM pozostaje w stanie aktywnym.',example:'tON = 2 ms i T = 5 ms: D = 40%.',use:'Sterowanie jasnością LED, wentylatorem, silnikiem i przetwornicą.',tip:'Średnie napięcie bywa proporcjonalne do wypełnienia, ale zależy też od obciążenia i topologii.'}
];

const categories=['Wszystkie',...new Set(DB.map(x=>x.cat))];
function renderList(){
 const q=$('fsSearch').value.trim().toLowerCase(),cat=$('fsCategory').value;
 const rows=DB.filter(x=>(cat==='Wszystkie'||x.cat===cat)&&(!q||Object.values(x).join(' ').toLowerCase().includes(q)));
 $('fsDetail').innerHTML=''; $('fsList').style.display='grid';
 $('fsList').innerHTML=rows.length?rows.map(x=>'<article class="card fsCard" data-fs="'+esc(x.s)+'"><div class="fsSymbol">'+esc(x.s)+'</div><h2>'+esc(x.name)+'</h2><div class="fsFormula">'+esc(x.formula)+'</div><span class="badge">'+esc(x.unit)+'</span><p class="muted small">'+esc(x.desc)+'</p></article>').join(''):'<div class="card"><h2>Brak wyników</h2><p>Zmień wyszukiwaną frazę lub kategorię.</p></div>';
 document.querySelectorAll('[data-fs]').forEach(b=>b.onclick=()=>openDetail(b.dataset.fs));
}
function openDetail(symbol){
 const x=DB.find(v=>v.s===symbol);if(!x)return;
 $('fsList').style.display='none';
 $('fsDetail').innerHTML='<div class="detailBox"><button class="secondary" id="fsBack">← Wróć do symboli</button><span class="badge" style="margin-left:8px">'+esc(x.cat)+'</span><h1 style="margin-top:14px"><span class="fsSymbol">'+esc(x.s)+'</span> — '+esc(x.name)+'</h1><div class="grid"><div class="card"><h2>Znaczenie</h2><p>'+esc(x.desc)+'</p><div class="fsUnits"><span class="fsUnit"><b>Jednostka:</b> '+esc(x.unit)+'</span></div><div class="fsFormula">'+esc(x.formula)+'</div></div><div class="card"><h2>🧮 Przykład obliczenia</h2><div class="result">'+esc(x.example)+'</div><h2 style="margin-top:16px">🛠️ Zastosowanie</h2><p>'+esc(x.use)+'</p></div></div><div class="note"><b>Wskazówka:</b> '+esc(x.tip)+'</div></div>';
 $('fsBack').onclick=()=>{renderList();$('formulasymbols').scrollIntoView({behavior:'smooth',block:'start'})};
 $('fsDetail').scrollIntoView({behavior:'smooth',block:'nearest'});
}

function setOut(id,html,bad=false){$(id).innerHTML='<div class="'+(bad?'danger':'result')+'">'+html+'</div>'}
function calcOhm(){
 const what=$('fsOhmWhat').value,U=num($('fsOhmU').value),I=num($('fsOhmI').value),R=num($('fsOhmR').value);let v,unit,work;
 if(what==='I'){if(!ok(U)||!ok(R)||R===0)return setOut('fsOhmOut','Podaj napięcie U i rezystancję R większą od zera.',true);v=U/R;unit='A';work='I = '+fmt(U)+' / '+fmt(R)}
 if(what==='U'){if(!ok(I)||!ok(R))return setOut('fsOhmOut','Podaj prąd I i rezystancję R.',true);v=I*R;unit='V';work='U = '+fmt(I)+' × '+fmt(R)}
 if(what==='R'){if(!ok(U)||!ok(I)||I===0)return setOut('fsOhmOut','Podaj napięcie U i prąd I różny od zera.',true);v=U/I;unit='Ω';work='R = '+fmt(U)+' / '+fmt(I)}
 setOut('fsOhmOut','<span class="fsResult">'+fmt(v)+' '+unit+'</span><br>'+work+' = '+fmt(v)+' '+unit);
}
function calcPower(){const U=num($('fsPowU').value),I=num($('fsPowI').value);if(!ok(U)||!ok(I))return setOut('fsPowOut','Podaj U i I.',true);setOut('fsPowOut','<span class="fsResult">'+fmt(U*I)+' W</span><br>P = '+fmt(U)+' V × '+fmt(I)+' A')}
function calcDivider(){const Vin=num($('fsDivVin').value),R1=num($('fsDivR1').value),R2=num($('fsDivR2').value);if(!ok(Vin)||!ok(R1)||!ok(R2)||R1+R2===0)return setOut('fsDivOut','Podaj poprawne wartości.',true);const o=Vin*R2/(R1+R2);setOut('fsDivOut','<span class="fsResult">Uwy = '+fmt(o)+' V</span><br>'+fmt(Vin)+' × '+fmt(R2)+' / ('+fmt(R1)+' + '+fmt(R2)+')')}
function calcEnergy(){const V=num($('fsEnV').value),Ah=num($('fsEnAh').value),W=num($('fsEnW').value);if(!ok(V)||!ok(Ah)||!ok(W)||W<=0)return setOut('fsEnOut','Podaj napięcie, pojemność oraz pobór mocy większy od zera.',true);const Wh=V*Ah,h=Wh/W;setOut('fsEnOut','<span class="fsResult">'+fmt(Wh)+' Wh ≈ '+fmt(h)+' h</span><br>Czas idealny; rzeczywisty będzie krótszy przez straty i ograniczenia baterii.')}
function calcReactance(){const f=num($('fsXf').value),value=num($('fsXval').value),kind=$('fsXkind').value,scale=num($('fsXscale').value);if(!ok(f)||f<=0||!ok(value)||value<=0)return setOut('fsXOut','Podaj dodatnie f i wartość elementu.',true);const base=value*scale,v=kind==='C'?1/(2*Math.PI*f*base):2*Math.PI*f*base;setOut('fsXOut','<span class="fsResult">X'+(kind==='C'?'ᴄ':'ᴸ')+' = '+fmt(v)+' Ω</span><br>Dla f = '+fmt(f)+' Hz.')}

function renderCalculators(){
 $('fsCalculators').innerHTML='<div class="card"><h1>🧮 Kalkulatory warsztatowe</h1><p class="muted">Możesz wpisywać przecinek albo kropkę dziesiętną.</p></div>'+
 '<div class="grid"><div class="card"><h2>Prawo Ohma</h2><label>Oblicz<select id="fsOhmWhat"><option value="I">I — prąd</option><option value="U">U — napięcie</option><option value="R">R — rezystancję</option></select></label><div class="fsCalcGrid"><label>U [V]<input id="fsOhmU" inputmode="decimal" value="12"></label><label>I [A]<input id="fsOhmI" inputmode="decimal" value="2"></label><label>R [Ω]<input id="fsOhmR" inputmode="decimal" value="6"></label></div><button class="primary" id="fsOhmBtn" style="margin-top:12px">Oblicz</button><div id="fsOhmOut"></div></div>'+
 '<div class="card"><h2>Moc P = U × I</h2><div class="fsCalcGrid"><label>U [V]<input id="fsPowU" inputmode="decimal" value="12"></label><label>I [A]<input id="fsPowI" inputmode="decimal" value="2"></label></div><button class="primary" id="fsPowBtn" style="margin-top:12px">Oblicz moc</button><div id="fsPowOut"></div></div></div>'+
 '<div class="grid"><div class="card"><h2>Dzielnik napięcia</h2><div class="fsCalcGrid"><label>Uwe [V]<input id="fsDivVin" inputmode="decimal" value="12"></label><label>R₁ [Ω]<input id="fsDivR1" inputmode="decimal" value="10000"></label><label>R₂ [Ω]<input id="fsDivR2" inputmode="decimal" value="10000"></label></div><button class="primary" id="fsDivBtn" style="margin-top:12px">Oblicz Uwy</button><div id="fsDivOut"></div></div>'+
 '<div class="card"><h2>Energia baterii i czas pracy</h2><div class="fsCalcGrid"><label>Napięcie [V]<input id="fsEnV" inputmode="decimal" value="18"></label><label>Pojemność [Ah]<input id="fsEnAh" inputmode="decimal" value="5"></label><label>Pobór [W]<input id="fsEnW" inputmode="decimal" value="45"></label></div><button class="primary" id="fsEnBtn" style="margin-top:12px">Oblicz</button><div id="fsEnOut"></div></div></div>'+
 '<div class="card"><h2>Reaktancja kondensatora lub cewki</h2><div class="fsCalcGrid"><label>Rodzaj<select id="fsXkind"><option value="C">Xᴄ — kondensator</option><option value="L">Xᴸ — cewka</option></select></label><label>f [Hz]<input id="fsXf" inputmode="decimal" value="1000"></label><label>Wartość<input id="fsXval" inputmode="decimal" value="1"></label><label>Przedrostek<select id="fsXscale"><option value="0.000001">µF / µH</option><option value="0.001">mF / mH</option><option value="1">F / H</option><option value="1e-9">nF / nH</option></select></label></div><button class="primary" id="fsXBtn" style="margin-top:12px">Oblicz X</button><div id="fsXOut"></div></div>'+
 '<div class="card"><h2>Przedrostki jednostek</h2><table class="fsPrefixTable"><thead><tr><th>Symbol</th><th>Nazwa</th><th>Mnożnik</th><th>Przykład</th></tr></thead><tbody><tr><td>G</td><td>giga</td><td>10⁹</td><td>1 GHz</td></tr><tr><td>M</td><td>mega</td><td>10⁶</td><td>1 MΩ</td></tr><tr><td>k</td><td>kilo</td><td>10³</td><td>1 kΩ = 1000 Ω</td></tr><tr><td>m</td><td>mili</td><td>10⁻³</td><td>1 mA = 0,001 A</td></tr><tr><td>µ</td><td>mikro</td><td>10⁻⁶</td><td>1 µF = 0,000001 F</td></tr><tr><td>n</td><td>nano</td><td>10⁻⁹</td><td>1 nF = 0,001 µF</td></tr><tr><td>p</td><td>piko</td><td>10⁻¹²</td><td>1000 pF = 1 nF</td></tr></tbody></table><div class="danger" style="margin-top:12px"><b>Uwaga:</b> M oznacza mega, a m oznacza mili — wielkość litery zmienia wynik milion razy.</div></div>';
 $('fsOhmBtn').onclick=calcOhm;$('fsPowBtn').onclick=calcPower;$('fsDivBtn').onclick=calcDivider;$('fsEnBtn').onclick=calcEnergy;$('fsXBtn').onclick=calcReactance;
 calcOhm();calcPower();calcDivider();calcEnergy();calcReactance();
}

$('fsCategory').innerHTML=categories.map(x=>'<option>'+esc(x)+'</option>').join('');
$('fsSearch').addEventListener('input',renderList);$('fsCategory').addEventListener('change',renderList);
renderList();renderCalculators();
})();
