(function(){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const tools=[
{name:'OpenBoardView',cat:'Schematy i BoardView',os:'Windows / Linux / macOS',devices:['Laptop','Konsola','Telefon','Płyta PCB'],faults:['Zwarcie','Brak zasilania','Brak obrazu','Uszkodzenie ścieżki'],interface:'Plik BoardView płyty: .brd, .bdv lub obsługiwany format.',use:'Wyświetlanie położenia elementów, sieci i połączeń na płycie. Pomaga przejść od oznaczenia elementu do wszystkich punktów tej samej linii.',steps:['Zdobądź plik BoardView dokładnie do numeru płyty i rewizji.','Otwórz plik i wyszukaj oznaczenie elementu albo nazwę sieci.','Kliknij pad, aby podświetlić połączoną sieć.','Porównaj punkty z płytą pod mikroskopem i wykonaj pomiary bez zasilania lub pod kontrolowanym zasilaniem.'],interpret:'Brak ciągłości między punktami tej samej sieci wskazuje przerwę, uszkodzony pad, przelotkę albo element szeregowy. Niska rezystancja linii może być prawidłowa — porównaj z dokumentacją i sprawną płytą.',limits:'BoardView nie jest pełnym schematem i może nie zawierać wartości elementów.',url:'https://github.com/OpenBoardView/OpenBoardView'},
{name:'KiCad Gerber Viewer',cat:'Schematy i BoardView',os:'Windows / Linux / macOS',devices:['Płyta PCB','Zasilacz','Audio','AGD'],faults:['Uszkodzenie ścieżki','Identyfikacja elementu','Naprawa po zalaniu'],interface:'Pliki Gerber, drill oraz projekty KiCad.',use:'Analiza warstw PCB, ścieżek, pól masy, przelotek i rozmieszczenia elementów.',steps:['Załaduj komplet warstw Gerber.','Włącz kolejno miedź górną, dolną i warstwy wewnętrzne.','Użyj podświetlenia i pomiaru odległości.','Porównaj z fizyczną płytą i zdjęciami przed naprawą.'],interpret:'Przebieg ścieżki pomaga ustalić dalszy punkt pomiarowy, zwłaszcza po korozji lub wyrwanym padzie.',limits:'Bez netlisty Gerber nie zawsze pokaże logiczną nazwę sieci.',url:'https://www.kicad.org/'},
{name:'UEFITool',cat:'BIOS i firmware',os:'Windows / Linux / macOS',devices:['Laptop','Komputer PC'],faults:['Brak startu','Uszkodzony BIOS','Restart','Brak obrazu'],interface:'Plik obrazu BIOS/UEFI odczytany programatorem lub pobrany od producenta.',use:'Przegląd struktury BIOS, regionów firmware, modułów UEFI i wpisów NVRAM.',steps:['Najpierw odczytaj kość i zachowaj co najmniej dwie zgodne kopie.','Otwórz kopię w UEFITool i sprawdź komunikaty parsera.','Wyszukaj moduł, GUID lub tekst.','Modyfikuj tylko kopię roboczą; przed zapisem zachowaj dane urządzenia.'],interpret:'Błędy parsera mogą wskazywać uszkodzony lub niepełny wsad, ale część komunikatów wynika ze specyficznej konstrukcji producenta.',limits:'Program nie potwierdza elektrycznej sprawności kości ani płyty.',url:'https://github.com/LongSoft/UEFITool'},
{name:'HxD Hex Editor',cat:'BIOS i firmware',os:'Windows',devices:['Laptop','Telewizor','Konsola','Router','AGD'],faults:['Uszkodzony wsad','Porównanie firmware','Brak startu'],interface:'Pliki BIN/ROM odczytane z pamięci.',use:'Porównanie binarne wsadów, wyszukiwanie tekstu i kontrola rozmiaru obrazu.',steps:['Pracuj na kopii pliku.','Sprawdź dokładny rozmiar i sumę kontrolną odczytów.','Użyj porównania plików dla dwóch odczytów tej samej kości.','Zapisuj zmiany do nowego pliku, nie nadpisuj oryginału.'],interpret:'Różne wyniki kolejnych odczytów sugerują problem z połączeniem, zasilaniem kości, klipsem lub programatorem.',limits:'Edycja pojedynczych bajtów bez znajomości struktury może trwale zablokować urządzenie.',url:'https://mh-nexus.de/en/hxd/'},
{name:'flashrom',cat:'Programatory pamięci',os:'Windows / Linux / macOS',devices:['Laptop','Komputer PC','Router','Płyta PCB'],faults:['Uszkodzony BIOS','Brak startu','Odzyskiwanie firmware'],interface:'Obsługiwany programator SPI oraz właściwe napięcie pamięci.',use:'Odczyt, identyfikacja, kasowanie, zapis i weryfikacja pamięci flash.',steps:['Sprawdź oznaczenie kości i napięcie 1,8 V albo 3,3 V.','Podłącz programator przy odłączonym zasilaniu urządzenia.','Wykonaj dwa odczyty i porównaj sumy.','Zapis wykonuj dopiero po zachowaniu oryginału.','Po zapisie uruchom pełną weryfikację.'],interpret:'Identyczne odczyty i poprawna weryfikacja potwierdzają transmisję, nie gwarantują jednak poprawności samego wsadu.',limits:'Nie wszystkie programatory i układy są obsługiwane; klips w układzie może być obciążany przez resztę płyty.',url:'https://www.flashrom.org/'},
{name:'AsProgrammer / NeoProgrammer',cat:'Programatory pamięci',os:'Windows',devices:['Laptop','Telewizor','Router','Konsola','AGD'],faults:['Uszkodzony BIOS','Brak startu','Uszkodzony firmware'],interface:'Najczęściej CH341A z adapterem 1,8/3,3 V i klipsem SOIC.',use:'Obsługa popularnych pamięci SPI/I²C: identyfikacja, odczyt, kasowanie, zapis i weryfikacja.',steps:['Sprawdź napięcie na wyjściu programatora przed podłączeniem.','Dobierz dokładny model kości albo zgodny układ z tej samej rodziny.','Odczytaj pamięć kilka razy i porównaj pliki.','Wykonaj kopię bezpieczeństwa.','Po zapisie użyj Verify i ponownego odczytu.'],interpret:'Same wartości FF lub 00 mogą oznaczać zły kontakt, blokadę, błędne napięcie albo pustą/uszkodzoną pamięć.',limits:'Wersje programów i listy układów różnią się; pobieraj je wyłącznie z zaufanego źródła. Nie zakładaj, że każdy CH341A podaje bezpieczne 3,3 V.',url:''},
{name:'XGpro / XGecu',cat:'Programatory pamięci',os:'Windows',devices:['Laptop','Telewizor','Konsola','Audio','AGD'],faults:['Uszkodzony firmware','Test pamięci','Kopiowanie układu'],interface:'Programator XGecu/TL866/T48/T56 i właściwy adapter.',use:'Programowanie EEPROM, SPI flash, NAND, mikrokontrolerów i wielu układów równoległych zależnie od sprzętu.',steps:['Zainstaluj oficjalny program i sterownik.','Wybierz dokładny układ oraz adapter.','Sprawdź orientację pinu 1.','Odczytaj ID i wykonaj kopie.','Kasuj, zapisz i zweryfikuj zgodnie z typem układu.'],interpret:'Błąd ID lub Verify zwykle oznacza kontakt, adapter, napięcie, zabezpieczenie albo uszkodzenie pamięci.',limits:'Zakres układów zależy od modelu programatora i adapterów.',url:'http://www.xgecu.com/'},
{name:'RT809H Software',cat:'Programatory pamięci',os:'Windows',devices:['Telewizor','Monitor','Laptop','Router'],faults:['Brak obrazu','Uszkodzony firmware','Uszkodzona pamięć eMMC/NAND'],interface:'Programator RT809H oraz odpowiednie przewody, ISP lub adaptery.',use:'Odczyt i zapis SPI, eMMC, NAND oraz wybranych układów stosowanych w TV i monitorach.',steps:['Zidentyfikuj pamięć i metodę: w układzie, ISP lub w adapterze.','Sprawdź napięcia i pinout.','Wykonaj pełną kopię przed każdą operacją.','Porównaj kolejne odczyty.','Zapisuj dopiero po zweryfikowaniu pliku i wariantu płyty.'],interpret:'Niestabilny odczyt przez ISP może wynikać z obciążenia linii przez płytę; czasem konieczny jest demontaż pamięci.',limits:'Funkcje zależą od wersji sprzętu, adaptera i aktualnej bazy układów.',url:''},
{name:'PuTTY',cat:'UART i terminal',os:'Windows / Linux',devices:['Router','Telewizor','Konsola','Płyta PCB','AGD'],faults:['Brak startu','Restart','Błąd firmware','Brak komunikacji'],interface:'Adapter USB–UART zgodny z poziomem 1,8/3,3/5 V; zwykle GND, RX i TX.',use:'Podgląd logu startowego urządzenia i interakcja z konsolą serwisową, jeśli jest dostępna.',steps:['Ustal GND, TX i napięcie logiki miernikiem/oscyloskopem.','Nie podłączaj VCC bez potrzeby.','Połącz TX urządzenia z RX adaptera i wspólną masę.','Wybierz port COM i typową prędkość, np. 115200 8N1.','Uruchom urządzenie i zapisz log.'],interpret:'Brak tekstu może oznaczać złą prędkość, zamienione RX/TX, brak startu CPU, reset lub niewłaściwy poziom napięcia.',limits:'Nie podłączaj adaptera TTL do prawdziwego RS‑232 ani do nieizolowanej strony sieciowej.',url:'https://www.chiark.greenend.org.uk/~sgtatham/putty/'},
{name:'Tera Term',cat:'UART i terminal',os:'Windows',devices:['Router','Telewizor','Konsola','Płyta PCB','AGD'],faults:['Brak startu','Restart','Błąd firmware','Aktualizacja serwisowa'],interface:'USB–UART lub port szeregowy.',use:'Terminal szeregowy z zapisem sesji, makrami i transferem plików przez wybrane protokoły.',steps:['Wybierz Serial oraz właściwy COM.','Ustaw baud, 8 bitów, brak parzystości, 1 stop i brak flow control, jeśli dokumentacja nie mówi inaczej.','Włącz zapis logu przed uruchomieniem płyty.','Porównaj miejsce zatrzymania z pełnym prawidłowym logiem.'],interpret:'Powtarzający się fragment logu wskazuje pętlę restartu; komunikat o pamięci, systemie plików lub napięciu kieruje do konkretnego bloku.',limits:'Nie wysyłaj poleceń kasowania/programowania bez kopii i dokumentacji.',url:'https://teratermproject.github.io/'},
{name:'PulseView / sigrok',cat:'Analizator logiczny',os:'Windows / Linux / macOS',devices:['Płyta PCB','Laptop','Telewizor','AGD','Router'],faults:['Brak komunikacji','I²C/SPI/UART','Błąd czujnika','Brak startu'],interface:'Obsługiwany analizator logiczny, np. zgodny FX2; wspólna masa i właściwe poziomy napięć.',use:'Rejestracja i dekodowanie UART, I²C, SPI, 1-Wire oraz innych wolnych magistral.',steps:['Sprawdź napięcie logiki i zakres wejść analizatora.','Podłącz GND oraz wybrane linie bez podawania zasilania.','Ustaw próbkowanie co najmniej kilka razy wyższe od częstotliwości sygnału.','Nagraj start urządzenia.','Dodaj właściwy dekoder i sprawdź adresy, dane oraz ACK/NACK.'],interpret:'Brak zegara oznacza brak aktywności mastera; brak ACK może wskazywać zasilanie, adres, przerwę, zwarcie albo uszkodzony układ slave.',limits:'Tani analizator nie jest oscyloskopem — nie pokaże jakości zboczy ani poziomów analogowych.',url:'https://sigrok.org/wiki/PulseView'},
{name:'Saleae Logic 2',cat:'Analizator logiczny',os:'Windows / Linux / macOS',devices:['Płyta PCB','Laptop','Telewizor','AGD','Router'],faults:['Brak komunikacji','I²C/SPI/UART','Błąd sterowania'],interface:'Analizator Saleae Logic i przewody pomiarowe.',use:'Wygodne nagrywanie, wyszukiwanie i dekodowanie wielu protokołów cyfrowych.',steps:['Ustaw wejścia i częstotliwość próbkowania.','Podłącz wspólną masę i kanały.','Zastosuj wyzwalanie lub dłuższy zapis startu.','Dodaj analizator protokołu.','Eksportuj dane do porównania ze sprawną płytą.'],interpret:'Porównaj sekwencję inicjalizacji, odpowiedzi urządzeń i moment wystąpienia błędu.',limits:'Używaj sprzętu zgodnego z dopuszczalnym napięciem wejściowym.',url:'https://www.saleae.com/downloads/'},
{name:'USB Device Tree Viewer',cat:'USB i porty',os:'Windows',devices:['Laptop','Komputer PC','Telefon','Kamera','Programator'],faults:['USB nie wykrywa','Zrywanie połączenia','Wolna transmisja','Błąd sterownika'],interface:'Urządzenie podłączone do portu USB.',use:'Pokazuje kontrolery, huby, deskryptory, prędkość połączenia, pobór deklarowany i błędy enumeracji.',steps:['Uruchom program jako administrator.','Podłącz urządzenie i odszukaj nową gałąź.','Sprawdź VID/PID, status portu i prędkość.','Porównaj zachowanie na innym porcie, kablu i komputerze.','Zapisz raport przed odłączeniem.'],interpret:'Brak enumeracji przy obecnym VBUS kieruje do linii D+/D−, CC, ESD, gniazda lub kontrolera; zejście do USB 2.0 może wskazywać kabel albo linie SuperSpeed.',limits:'Program nie mierzy napięcia, jakości sygnału ani rzeczywistego poboru.',url:'https://www.uwe-sieber.de/usbtreeview_e.html'},
{name:'Wireshark + USBPcap',cat:'USB i sieć',os:'Windows / Linux / macOS',devices:['Router','Komputer PC','Urządzenie USB','Smart TV'],faults:['Błąd komunikacji','Problemy sieciowe','Nieudana aktualizacja'],interface:'Interfejs sieciowy albo przechwytywanie USB przez zgodny sterownik.',use:'Analiza pakietów sieciowych oraz wybranej komunikacji USB.',steps:['Wybierz właściwy interfejs.','Ustaw filtr zawężający urządzenie lub protokół.','Rozpocznij zapis przed wystąpieniem usterki.','Zatrzymaj i oznacz moment błędu.','Porównaj żądania, odpowiedzi, retransmisje i kody błędów.'],interpret:'Powtarzane żądania bez odpowiedzi wskazują utratę komunikacji, problem sterownika, firmware albo fizycznego łącza.',limits:'Przechwytywanie może zawierać dane prywatne; zapisuj tylko niezbędny ruch.',url:'https://www.wireshark.org/'},
{name:'Android Platform Tools – ADB/Fastboot',cat:'Telefon i tablet',os:'Windows / Linux / macOS',devices:['Telefon','Tablet'],faults:['Bootloop','Błąd aplikacji','Brak startu systemu','Problem USB'],interface:'USB, właściwy sterownik i — dla ADB — autoryzowane debugowanie.',use:'Logcat, wykrywanie urządzenia, tryb recovery/bootloader i oficjalne operacje serwisowe.',steps:['Zainstaluj oficjalne Platform Tools.','Sprawdź poleceniem adb devices lub fastboot devices.','Zapisz logcat podczas występowania usterki.','Nie odblokowuj bootloadera ani nie flashuj bez kopii danych i pewnego obrazu dla modelu.'],interpret:'Urządzenie widoczne w Fastboot, ale nie w systemie, wskazuje problem systemu/partycji; brak wykrycia w obu trybach kieruje także do USB i zasilania.',limits:'Część operacji kasuje dane lub wymaga odblokowania producenta.',url:'https://developer.android.com/tools/releases/platform-tools'},
{name:'Apple Devices / iTunes',cat:'Telefon i tablet',os:'Windows / macOS',devices:['iPhone','iPad'],faults:['Bootloop','Tryb recovery','Błąd aktualizacji','Brak wykrywania USB'],interface:'Sprawny przewód USB i komputer.',use:'Wykrywanie, kopia, aktualizacja i odtwarzanie urządzeń Apple oraz odczyt kodu błędu procesu.',steps:['Najpierw sprawdź kabel, port i złącze urządzenia.','Wykonaj kopię, jeśli system pozwala.','Spróbuj aktualizacji bez kasowania danych.','Odtwarzanie wykonuj tylko świadomie, ponieważ usuwa dane.','Zapisz dokładny kod błędu.'],interpret:'Powtarzalny kod błędu i stały etap przerwania pomagają rozdzielić problem połączenia, pamięci, basebandu, zasilania lub systemu.',limits:'Program nie naprawi usterki sprzętowej; odtwarzanie może skasować dane.',url:'https://support.apple.com/guide/devices-windows/welcome/windows'},
{name:'CrystalDiskInfo',cat:'Dyski i pamięć',os:'Windows',devices:['Laptop','Komputer PC','Dysk USB'],faults:['Wolna praca','Zawieszanie','Błędy dysku','Utrata danych'],interface:'Dysk SATA/NVMe/USB; mostek USB musi przekazywać SMART.',use:'Odczyt SMART, temperatury, czasu pracy i liczników błędów dysku.',steps:['Uruchom program i wybierz właściwy dysk.','Zapisz pełne wartości RAW atrybutów.','Sprawdź temperaturę, błędy nośnika i interfejsu.','Przy ostrzeżeniu wykonaj kopię danych przed testami obciążeniowymi.'],interpret:'Rosnące sektory niestabilne/realokowane lub błędy NVMe są alarmem; same błędy CRC częściej wskazują kabel lub połączenie.',limits:'Status „dobry” nie wyklucza wszystkich usterek ani nagłej awarii.',url:'https://crystalmark.info/en/software/crystaldiskinfo/'},
{name:'TestDisk / PhotoRec',cat:'Dyski i pamięć',os:'Windows / Linux / macOS',devices:['Dysk USB','Karta pamięci','Laptop','Komputer PC'],faults:['Utrata partycji','Usunięte pliki','Uszkodzony system plików'],interface:'Nośnik podłączony stabilnie, najlepiej z obrazem sektorowym.',use:'Odzyskiwanie partycji i plików z nośników logicznie uszkodzonych.',steps:['Przy cennych danych najpierw wykonaj obraz uszkodzonego nośnika.','Pracuj na kopii, nie na oryginale.','Użyj Analyse do struktury partycji lub PhotoRec do odzysku plików.','Zapisuj odzyskane dane na innym dysku.'],interpret:'Rosnące błędy odczytu oznaczają problem sprzętowy — przerwij wielokrotne skanowanie i rozważ profesjonalny odzysk.',limits:'Nadpisane dane są nieodzyskiwalne; program nie naprawia mechaniki dysku.',url:'https://www.cgsecurity.org/'},
{name:'MemTest86',cat:'Komputer i laptop',os:'Uruchamiany z USB',devices:['Laptop','Komputer PC'],faults:['Restart','BSOD','Brak stabilności','Błędy instalacji'],interface:'Bootowalny pendrive.',use:'Test pamięci RAM poza systemem operacyjnym.',steps:['Przygotuj USB zgodnie z instrukcją.','Przywróć ustawienia RAM do domyślnych przed testem.','Wykonaj kilka pełnych przebiegów.','Testuj moduły i sloty osobno, jeśli wystąpią błędy.'],interpret:'Błąd wskazuje niestabilność toru pamięci, ale winny może być moduł, slot, kontroler, ustawienia, zasilanie lub temperatura.',limits:'Brak błędów nie gwarantuje stabilności w każdych warunkach.',url:'https://www.memtest86.com/'},
{name:'HWiNFO',cat:'Komputer i laptop',os:'Windows',devices:['Laptop','Komputer PC'],faults:['Przegrzewanie','Wyłączanie','Throttling','Niestabilne zasilanie'],interface:'Czujniki płyty i system operacyjny.',use:'Rejestracja temperatur, taktowań, limitów mocy, wentylatorów i wybranych napięć.',steps:['Uruchom Sensors-only.','Włącz logowanie do pliku.','Odtwórz usterkę kontrolowanym obciążeniem.','Sprawdź temperatury, limity throttling i spadki taktowania.','Porównaj czas zdarzeń z objawem.'],interpret:'Wysoka temperatura i aktywny thermal throttling wskazują układ chłodzenia; nagły zanik odczytu może oznaczać wyłączenie zasilania.',limits:'Napięcia raportowane przez czujniki programowe mogą być niedokładne — potwierdź miernikiem.',url:'https://www.hwinfo.com/'},
{name:'Audacity',cat:'Audio',os:'Windows / Linux / macOS',devices:['Audio','Wzmacniacz','Mikrofon'],faults:['Brak dźwięku','Szum','Charczenie','Różnica kanałów'],interface:'Wejście/wyjście audio komputera, właściwy tłumik lub interfejs pomiarowy.',use:'Generowanie tonu, nagrywanie sygnału, analiza widma i porównanie kanałów.',steps:['Nie podłączaj wyjścia głośnikowego bezpośrednio do wejścia mikrofonowego.','Ustaw bezpieczny poziom i ton, np. 1 kHz.','Śledź sygnał przez kolejne stopnie.','Nagraj oba kanały i porównaj amplitudę oraz widmo.'],interpret:'Harmoniczne, clipping, przydźwięk 50/100 Hz i różnica kanałów pomagają wskazać zasilanie, punkt pracy lub uszkodzony stopień.',limits:'Karta dźwiękowa ma ograniczony zakres i wspólną masę; do końcówek mocy użyj właściwego interfejsu/sondy.',url:'https://www.audacityteam.org/'},
{name:'Room EQ Wizard (REW)',cat:'Audio',os:'Windows / Linux / macOS',devices:['Audio','Głośnik','Wzmacniacz'],faults:['Zniekształcenia','Nierówne pasmo','Problem zwrotnicy','Różnica kanałów'],interface:'Interfejs audio i mikrofon pomiarowy albo bezpieczne połączenie liniowe.',use:'Pomiary pasma, zniekształceń, poziomu i odpowiedzi impulsowej.',steps:['Skalibruj interfejs i poziomy.','Wykonaj pomiar przy małej mocy.','Porównaj kanały lub sprawny egzemplarz.','Szukaj załamań pasma i wzrostu THD.'],interpret:'Ubytek pasma może wskazywać głośnik, kondensator zwrotnicy lub tor wzmacniacza; wzrost THD przy małym poziomie sugeruje uszkodzenie.',limits:'Wynik akustyczny zależy również od pomieszczenia i ustawienia mikrofonu.',url:'https://www.roomeqwizard.com/'}
];

function init(){
 const $=id=>document.getElementById(id); if(!$('pcToolList'))return;
 const cats=[...new Set(tools.map(x=>x.cat))].sort();
 const devices=[...new Set(tools.flatMap(x=>x.devices))].sort();
 const faults=[...new Set(tools.flatMap(x=>x.faults))].sort();
 $('pcToolCat').innerHTML='<option value="all">Wszystkie kategorie</option>'+cats.map(x=>'<option>'+esc(x)+'</option>').join('');
 $('pcDevice').innerHTML='<option value="all">Wszystkie urządzenia</option>'+devices.map(x=>'<option>'+esc(x)+'</option>').join('');
 $('pcFault').innerHTML='<option value="all">Wszystkie objawy</option>'+faults.map(x=>'<option>'+esc(x)+'</option>').join('');
 function renderDetail(x){
  $('pcToolDetail').innerHTML='<div class="detailBox"><span class="badge">'+esc(x.cat)+'</span><span class="badge">'+esc(x.os)+'</span><h2>'+esc(x.name)+'</h2><p><b>Zastosowanie:</b> '+esc(x.use)+'</p><div class="note"><b>🔌 Wymagane połączenie / dane</b><br>'+esc(x.interface)+'</div><div class="grid" style="margin-top:12px"><div class="card"><h3>Obsługa krok po kroku</h3>'+x.steps.map((v,i)=>'<div class="step"><b>'+(i+1)+'.</b> '+esc(v)+'</div>').join('')+'</div><div class="card"><h3>Interpretacja wyniku</h3><p>'+esc(x.interpret)+'</p><div class="danger"><b>Ograniczenia i bezpieczeństwo</b><br>'+esc(x.limits)+'</div></div></div>'+(x.url?'<button class="primary" id="pcOfficial">Oficjalna strona programu ↗</button>':'<div class="result"><b>Źródło programu:</b> użyj strony producenta urządzenia/programatora albo zaufanego repozytorium.</div>')+'</div>';
  if(x.url)$('pcOfficial').onclick=()=>window.open(x.url,'_blank','noopener');
  $('pcToolDetail').scrollIntoView({behavior:'smooth',block:'start'});
 }
 function render(){
  const q=$('pcToolSearch').value.trim().toLowerCase(),cat=$('pcToolCat').value,dev=$('pcDevice').value,fault=$('pcFault').value;
  const rows=tools.filter(x=>(cat==='all'||x.cat===cat)&&(dev==='all'||x.devices.includes(dev))&&(fault==='all'||x.faults.includes(fault))&&(!q||JSON.stringify(x).toLowerCase().includes(q)));
  $('pcToolCount').textContent='Znaleziono: '+rows.length+' z '+tools.length+' programów i narzędzi';
  $('pcQuickResult').innerHTML=(dev==='all'&&fault==='all')?'Wybierz urządzenie i objaw — otrzymasz krótszą listę.':rows.length?'<b>Najlepsze dopasowania:</b> '+rows.slice(0,5).map(x=>esc(x.name)).join(' • '):'Brak dokładnego dopasowania. Wybierz szerszy filtr lub wpisz inną frazę.';
  $('pcToolList').innerHTML=rows.map(x=>'<div class="card diagItem" data-pctool="'+tools.indexOf(x)+'"><span class="badge">'+esc(x.cat)+'</span><span class="badge">'+esc(x.os)+'</span><h2>'+esc(x.name)+'</h2><p>'+esc(x.use)+'</p><p class="muted small"><b>Urządzenia:</b> '+esc(x.devices.join(', '))+'</p></div>').join('')||'<div class="card"><p class="muted">Brak wyników dla wybranych filtrów.</p></div>';
  document.querySelectorAll('[data-pctool]').forEach(el=>el.onclick=()=>renderDetail(tools[+el.dataset.pctool]));
 }
 ['pcToolSearch','pcToolCat','pcDevice','pcFault'].forEach(id=>$(id).addEventListener(id==='pcToolSearch'?'input':'change',render));
 render();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
